### ISSUE TITLE
NSC - notizie storico critiche

### ISSUE THREAD

**Issue by fguernaccini** [ICCD-MiBACT/ArCo#102]
ciao,
segnalo che le notizie storico critiche (campo mappato su https://w3id.org/arco/ontology/context-description/historicalInformation) sono trasformate in LOD solo per i beni naturalistici e per i beni archeologici che però risultano sempre vuoti
http://dati.beniculturali.it/sparql?default-graph-uri=&query=select+distinct+*+where++%7B%0D%0A%3Fs+%3Chttps%3A%2F%2Fw3id.org%2Farco%2Fontology%2Fcontext-description%2FhistoricalInformation%3E+%3Fo%0D%0A%7D&format=text%2Fhtml&timeout=0&debug=on
Confrontando le schede di catalogo, ci risulta che questo bene ha il campo compilato ma nell'RDF non c'è
https://w3id.org/arco/resource/HistoricOrArtisticProperty/0300180383

**Comment by margherita-porena** [comment]
The issue has been solved with commit 66379fe
