### ISSUE TITLE
STCC

### ISSUE THREAD

**Issue by fguernaccini** [ICCD-MiBACT/ArCo#103]
Segnalo che nell'ontologia, tra i named individual sullo stato di conservazione, non sono disponibili i valori:

- ottimo

- sufficiente

- pessimo

**Comment by margherita-porena** [comment]
Sono stati aggiunti i termini ottimo e pessimo, mentre il termine sufficiente era già indicato come Stato di conservazione discreto. Sono state aggiornate anche le regole xslt per la rappresentazione di queste nuove entità.
Commit b4b63a4
