### ISSUE TITLE
Address ITALIA

### ISSUE THREAD

**Issue by fguernaccini** [ICCD-MiBACT/ArCo#104]
Ciao,
vi segnalo questa uri: https://w3id.org/arco/resource/Address/d41d8cd98f00b204e9800998ecf8427e  
Vedendo l'elenco delle label, delle city collegate e delle relazioni inverse ci sono dei problemi, non so dirvi da cosa siano causati

**Comment by margherita-porena** [comment]
The issue has been solved with commit c0dc1c9
