### ISSUE TITLE
missing rdf:type

### ISSUE THREAD

**Issue by oibaf** [ICCD-MiBACT/ArCo#106]
**Indicare quali parti del progetto sono coinvolte nel bug: ontologia, knowledge graph, rdfizer**

rdfizer

**Descrivere il problema**

l'analisi dei dati prodotti dalla procedura di trasformazione rileva l'assenza della tripla con predicato rdf:type per alcune delle entità descritte (almeno in alcuni casi l'iri non compare mai come soggetto di una tripla e potrebbe trattarsi di una incoerenza nella costruzione dell'iri nel caso si presenti come soggetto o oggetto)

**Descrivere come riprodurre il problema**

di seguito un elenco (credo esaustivo per tipologia, ma i casi sono migliaia) di identificativi di sistema ed iri

ICCD13706168 https://w3id.org/arco/resource/AgentRole/1201339844-archaeological-field-survey-1-scientific-directora0b4f79763181c48b0b5c81967e44a13

ICCD13771531 https://w3id.org/arco/resource/ArchivalSuberies/1201348081-avori

ICCD12442199 https://w3id.org/arco/resource/ConstructionDesign/2000240364-d41d8cd98f00b204e9800998ecf8427e

ICCD9706110 https://w3id.org/arco/resource/ConstructionPart/0900385690-part-intero-bene

ICCD8536763 https://w3id.org/arco/resource/CulturalEntityTechnicalStatus/0500274502

ICCD8243314 https://w3id.org/arco/resource/Edition/0900344190-1691-fi-firenze

ICCD13742842 https://w3id.org/arco/resource/Measurement/0800649198-1-

ICCD8354733 https://w3id.org/arco/resource/PreparatoryWork/0800459105-negativo

ICCD8345038 https://w3id.org/arco/resource/RelatedWorkSituation/0800087391-related-cultural-property-1-1

ICCD9066183 https://w3id.org/arco/resource/RoofStructure/1400075034-

ICCD13589825 https://w3id.org/arco/resource/TimeIndexedRole/0800366431-460ca2dd20add6803826043ca480f926

**Comportamento atteso**

corretta implementazione delle entità o degli iri

**Informazioni aggiuntive**

**Comment by margherita-porena** [comment]
The issue has been solved with commit 441 aded
