### ISSUE TITLE
collegamenti tra risorse

### ISSUE THREAD

**Issue by oibaf** [ICCD-MiBACT/ArCo#107]
**Indicare quali parti del progetto sono coinvolte nel bug: ontologia, knowledge graph, rdfizer**

rdfizer

**Descrivere il problema**

le seguenti risorse, generate dalla trasformazione dei dati xml estratti via oai, risultano sprovviste di collegamento alle entità pertinenti (forse collegato a #106)

**Descrivere come riprodurre il problema**

di seguito un elenco (credo esaustivo per tipologia, ma i casi sono migliaia) di identificativi di sistema ed iri

ICCD13741541 https://w3id.org/arco/resource/CulturalEntityTechnicalStatus/1201254197-8-part-fodero

ICCD13774330 https://w3id.org/arco/resource/FlooringLayout/0300090737-a-riquadri

ICCD13544021 https://w3id.org/arco/resource/Foundations/2000047800-5e08ca9e36ec4e8e0cf7f5f5b706ac4f

ICCD9706237 https://w3id.org/arco/resource/HorizontalElement/0900402965A-c15f61171e6265ffe82913c12ac4b764

ICCD9919560 https://w3id.org/arco/resource/Layout/0800486542-

ICCD8377240 https://w3id.org/arco/resource/PreparatoryOrFinalWork/0800082878-negativo

ICCD13658399 https://w3id.org/arco/resource/ProtectiveMeasure/0700110921-protective-measure-1

ICCD9706257 https://w3id.org/arco/resource/Roof/0900385695-17f39b557b305ad91e67b685b648e1ae

ICCD9705868 https://w3id.org/arco/resource/RoofStructure/0900402968A-capriate

ICCD9702825 https://w3id.org/arco/resource/TimeIndexedRole/0900173340A-0-154372575cedbf20dd62cb089d91b266

ICCD9706257 https://w3id.org/arco/resource/VerticalElement/0900385695-17f39b557b305ad91e67b685b648e1ae

**Comportamento atteso**

presenza del collegamento alla risorsa pertinente

**Informazioni aggiuntive**

**Comment by oibaf** [comment]
ad integrazione di quanto descritto in precedenza, di seguito un elenco rappresentativo dei casi (anche qui migliaia) in cui la procedura segnala una interruzione (e non l'assenza) dei collegamenti nel tentativo di risalire alla risorsa principale

ICCD8354733 https://w3id.org/arco/resource/Dating/0800459105-negativo
ICCD8354733 https://w3id.org/arco/resource/Event/0800459105-negativo-creation
ICCD13573322 https://w3id.org/arco/resource/Inventory/0800649579-preparatory-final-work-inventory-n_001822
ICCD8354733 https://w3id.org/arco/resource/PreparatoryOrFinalWork/0800459105-negativo
ICCD13231443 https://w3id.org/arco/resource/Subject/53323bdf9b4dbab282eee20017b5bd3f
ICCD8354649 https://w3id.org/arco/resource/Title/0800459063-preparatory-final-work-title-cavazzola-paolo-morando-1486-1522-portrait-de-dame-bergame-acad-carrara

**Comment by margherita-porena** [comment]
The issue has been solved with: 
commit 4a76079
commit e862d54
commit 4a76079
