### ISSUE TITLE
composizioni IRI dal dato linkEmm estratto via oai

### ISSUE THREAD

**Issue by oibaf** [ICCD-MiBACT/ArCo#108]
**Indicare quali parti del progetto sono coinvolte nel bug: ontologia, knowledge graph, rdfizer**

rdfizer

**Descrivere il problema**

il dato estratto dall'elemento linkEmm contenuto nelle entità multimediali lette via oai, andrebbe trattato per la presenza di caratteri non idonei alla composizione dell'IRI, diversamente le triple vengono scartate nella fase di importazione sull'endpoint

**Descrivere come riprodurre il problema**

ad esempio la scheda di catalogo con identificativo di sistema ICCD13396580 collegata alla EMM ICCD13270683 riproduce negli oggetti delle triple generate

<http://www.sigecweb.beniculturali.it/images/fullsize/ICCD1038953/ICCD13270683_N. 02477.jpg>

 il contenuto di linkEmm

<linkEmm>http://www.sigecweb.beniculturali.it/images/fullsize/ICCD1038953/ICCD13270683_N. 02477.jpg</linkEmm>

**Comportamento atteso**

la codifica dei caratteri non ammessi, nell'esempio indicato

<http://www.sigecweb.beniculturali.it/images/fullsize/ICCD1038953/ICCD13270683_N.%2002477.jpg>

**Informazioni aggiuntive**

ora il caso segnalato contiene anche la tripla corretta inserita via sql

**Comment by luigi-asprino** [comment]
Nel commit 6796256c2a3dc92eacee6424555394c1efdd6346 ho aggiunto l'escaping (tramite percent encoding) delle URL provenienti dalle schede EMM prima di essere restituiti.

**Comment by oibaf** [comment]
probabilmente andrebbe eliminato il carattere '#' nel primo parametro di PercentEscaper, nei [casi presenti](https://dati.beniculturali.it/sparql?query=select+distinct+%3Fy+%7B+graph+%3Chttps%3A%2F%2Fw3id.org%2Farco%2Fdata%3E+%7B%0D%0A%0D%0A+%3Fs+a-cat%3AisDescribedByCatalogueRecord+%3Fx%0D%0A++%3B+foaf%3Adepiction+%3Fy%0D%0A%0D%0A+filter+%28contains%28str%28%3Fy%29%2C%22%23%22%29%29%0D%0A%0D%0A%7D%7D) sembra opportuna la codifica
