### ISSUE TITLE
Integrazione XSLT per la mappatura dei Contenitori fisici e giuridici

### ISSUE THREAD

**Issue by ICCD-MiBACT** [ICCD-MiBACT/ArCo#109]
In RDFsizer va integrato il file XSL per la produzione dei LOD dei contenitori fisici e giuridici che dovrebbe essere già nella vostra disponibilità

**Comment by oibaf** [comment]
allegate le trasformazioni xslt e gli ultimi dati per la pubblicazione rdf

[trasformazioni CF e CG.zip](https://github.com/ICCD-MiBACT/ArCo/files/5196044/trasformazioni.CF.e.CG.zip)

**Comment by margherita-porena** [comment]
The issue has been closed
