### ISSUE TITLE
Stesso CIS con due URI differenti

### ISSUE THREAD

**Issue by ICCD-MiBACT** [ICCD-MiBACT/ArCo#110]
RDFsizer crea due CIS per lo stesso luogo (stessa denominazione "Museo Nazionale del Compendio Garibaldino di Caprera"). Potete verificare perchè accade e se ce ne sono degli altri?
Di seguito le URI:
https://dati.beniculturali.it/lodview-arco/resource/CulturalInstituteOrSite/ebff67f63ae3c93252c39005e840072a.html
e
https://dati.beniculturali.it/lodview-arco/resource/CulturalInstituteOrSite/7484fbd0c8c56a9c875f0519dd431557.html

**Comment by margherita-porena** [comment]
Dal controllo effettuato sulle schede dei beni è emerso che la creazione delle due uri diverse è data dal fatto che in un caso è stata inserita, oltre a Provincia e Comune, anche la Località, mentre nel secondo caso questo dato non è stato indicato.
Di seguito due esempi di schede:
ICCD13162273 
<PVCP hint="Provincia" >OT</PVCP>
<PVCC hint="Comune" >La Maddalena</PVCC>

ICCD8531189
<PVCP hint="Provincia" >OT</PVCP>
<PVCC hint="Comune" >La Maddalena</PVCC>
<PVCL hint="Localita'" >Isola di Caprera</PVCL>

**Comment by luigi-asprino** [comment]
Mettiamo le schede in quarantena?

**Comment by ICCD-MiBACT** [comment]
Si e avvisate le colleghe del Catalogo

**Comment by margherita-porena** [comment]
Ciao Luigi, stavo per l'appunto scrivendo ad Antonella Negri per sapere se
possiamo metterle in quarantena o meno, quando mi risponde ti aggiorno!

Il giorno gio 10 set 2020 alle ore 10:38 luigi-asprino <
notifications@github.com> ha scritto:
