### ISSUE TITLE
recupero link alla scheda PDF anche nei LOD

### ISSUE THREAD

**Issue by ICCD-MiBACT** [ICCD-MiBACT/ArCo#111]
Occorre prevedere il link alla scheda di catalogo completa in formato PDF anche nei nostri LOD.
Il Link alla scheda al momento è nel tag dc:source  nelle schede OAI in formato Dublin core.
Ad esempio, qui http://catalogo.beniculturali.it/oaitarget/OAIHandler?verb=ListRecords&metadataPrefix=oai_dc 

<dc:source xsi:type="pico:Anchor" >title=consulta la scheda catalografica; URL=http://www.catalogo.beniculturali.it/sigecSSU_FE/dettaglioScheda.action?keycode=ICCD2962864</dc:source>

la stesa proprietà Dublin core può essere usata anche in RDF

**Comment by margherita-porena** [comment]
The issue has been closed with commit a9fbf85

**Comment by alechiaretti** [comment]
Con questa modifica si aggiunge il collegamento a Sigec a tutte le risorse create con rdfizer. Però non si considerano le risorse che non sono presenti in Sigec.
I dati che provengono dalla Regiona Lombardia non sono presenti in Sigec, quindi si crea un dc:source che punta a una URL Sigec che non esiste.

Come soluzione, si potrebbe creare un elemento in _record/header_ in cui si segnala il sistema o dataset di provenienza, e in base a questo prevedere quando si creano o no certe proprietà?
