### ISSUE TITLE
collegamento del bene all'autore

### ISSUE THREAD

**Issue by oibaf** [ICCD-MiBACT/ArCo#112]
**Indicare quali parti del progetto sono coinvolte nel problema: ontologia, knowledge graph, rdfizer**

rdfizer

**Descrivere il problema**

il collegamento tra bene e autore non è consistente nei due predicati <https://w3id.org/arco/ontology/context-description/hasAuthor> e <http://data.cochrane.org/ontologies/pico/author>

**Descrivere come riprodurre il problema**

ad esempio https://w3id.org/arco/resource/HistoricOrArtisticProperty/0900288940

**Comportamento atteso**

collegamenti consistenti

**Comment by margherita-porena** [comment]
The issue has been solved with commit 75239f3
