### ISSUE TITLE
Recupero valore keycode da OAI

### ISSUE THREAD

**Issue by ICCD-MiBACT** [ICCD-MiBACT/ArCo#114]
Sarebbe molto utile, anche considerando come vengono prodotti i PDF dalle schede di catalogo, poter recuperare nei LOD  il keycode del SIGEC in un elemento dell'ontologia dedicato agli altri codici.
Il keycode (es: ICCD11747888) è presente come valore di OAI Record
OAI Record: oai:oaicat.iccd.org:@**ICCD11747888**@

nella URL
http://catalogo.beniculturali.it/oaitarget/OAIHandler?verb=GetRecord&metadataPrefix=oai_dc&identifier=oai:oaicat.iccd.org:@**ICCD11747888**@/xml

e come OAI Identifier di OAI Record Header​.

Si riesce quindi a recuperare questo dato e "inglobarlo" nei LOD?

**Comment by Valentina10** [comment]
Sono questi i codici di cui parli?

*QUERY*
select distinct ?catalogueRecord ?code where { ?catalogueRecord a-cat:systemRecordCode ?code }

*RESULTS*
http://dati.beniculturali.it/sparql?default-graph-uri=&query=select+distinct+%3FcatalogueRecord+%3Fcode+where+%7B%0D%0A%0D%0A+%3FcatalogueRecord+a-cat%3AsystemRecordCode+%3Fcode%0D%0A%0D%0A%7D%0D%0A&format=text%2Fhtml&timeout=0&debug=on

**Comment by chiaraven** [comment]
Si, sono una scimmia, avevo già mandato email ma mi sono scordata di
aggiornare github

Perdono!



Chiara Veninata


Il giorno mer 23 set 2020 alle ore 15:43 Valentina Carriero <
notifications@github.com> ha scritto:

**Comment by ICCD-MiBACT** [comment]
Si hai ragione, poi chiudere la issue,,,
