### ISSUE TITLE
URI risorse senza campo NCTN

### ISSUE THREAD

**Issue by alechiaretti** [ICCD-MiBACT/ArCo#115]
**Indicare quali parti del progetto sono coinvolte nel bug: ontologia, knowledge graph, rdfizer**
rdfizer

**Descrivere il problema**
La trasformazione non gestisce bene schede che sono senza campo _NCTN Numero catalogo generale_.

**Descrivere come riprodurre il problema**
Questo è un file di esempio che uso per provare la trasformazione https://drive.google.com/file/d/1ODGYrzC-u5HxT8OT_VvliCy2O9HqKCAl/view?usp=sharing
I dati di origine sono in https://www.dati.lombardia.it/Cultura/Architetture/kf9b-rj2t/data

**Comportamento atteso**
Usare il campo _ACC Altro codice_ per costruire le URI nel caso in cui nella scheda di origine non si trova NCTN.

**Informazioni aggiuntive**
Sto lavorando sulla trasformazione dei dati della Regione Lombardia. Questi dati sono in un sistema locale, quindi gli ID delle schede vanno a finire nel campo _ACC Altro codice_ e non in NCTN.
Apro questa issue in base a conversazioni con Chiara Veninata.

**Comment by ICCD-MiBACT** [comment]
Questa situazione si potrebbe in teoria verificare tutte le volte che sono presenti open data di schede di beni culturali senza numero culturale, cosa che purtroppo è abbastanza frequente. Quindi concordo con le indicazioni di Alessandro Chiaretti riguardo il comportamento atteso da RDFsizer.

**Comment by margherita-porena** [comment]
The issue has been solved with commit a9fbf85
