### ISSUE TITLE
Gestione campo STCR Scheda A 3.0

### ISSUE THREAD

**Issue by alechiaretti** [ICCD-MiBACT/ArCo#116]
**Indicare quali parti del progetto sono coinvolte nel bug: ontologia, knowledge graph, rdfizer**
rdfizer

**Descrivere il problema**
Nella trasformazione di rdfizer non si recupera il campo _STCR Riferimento alla parte_ (parte di _STC Stato di conservazione_) che si trova nella Scheda A 3.0

**Descrivere come riprodurre il problema**
Esempio di un file xml della scheda A con il campo STCR 
https://drive.google.com/file/d/1ODGYrzC-u5HxT8OT_VvliCy2O9HqKCAl/view?usp=sharing

**Comportamento atteso**
Recuperare il campo e creare le triple in base alle ontologie ArCo.

**Informazioni aggiuntive**

**Comment by margherita-porena** [comment]
The issue has been solved with commit 3861ebf
