### ISSUE TITLE
Gestione campo RVER

### ISSUE THREAD

**Issue by alechiaretti** [ICCD-MiBACT/ArCo#117]
**Indicare quali parti del progetto sono coinvolte nel bug: ontologia, knowledge graph, rdfizer**
rdfizer

**Descrivere il problema**
Nella trasformazione di rdfizer non si recupera il campo _RVER Codice bene radice_ (parte di RVE Struttura complessa) che si trova almeno nelle schede A e RA 3.0

**Descrivere come riprodurre il problema**
Esempio di un file xml della scheda A con il campo RVER
https://drive.google.com/file/d/1CdzEsTP3w-lNjQ9WmVms6ZV-MxAHcvh8/view?usp=sharing

**Comportamento atteso**
Recuperare il campo e creare le triple in base alle ontologie ArCo.

**Informazioni aggiuntive**
Questo campo è importante perchè permette di creare la relazione nei casi di beni complessi (collegamento dalla scheda figlio alla scheda padre).

**Comment by margherita-porena** [comment]
The issue has been solved with commit 64e7fa4
