### ISSUE TITLE
Gestione estremi cronologici Scheda A 3.0

### ISSUE THREAD

**Issue by alechiaretti** [ICCD-MiBACT/ArCo#118]
**Indicare quali parti del progetto sono coinvolte nel bug: ontologia, knowledge graph, rdfizer**
rdfizer

**Descrivere il problema**
La trasformazione non gestisce bene i casi in cui gli estremi cronologici sono di tipo diverso: invece di creare un solo tiapit:TimeInterval con il range delle date, ne crea uno per ogni estremo.
Esempio dati input:
```
<REL hint="CRONOLOGIA, ESTREMO REMOTO">
   <RELI hint="Data">1786</RELI>
</REL>
<REV hint="CRONOLOGIA, ESTREMO RECENTE">
   <REVS hint="Secolo">XVIII</REVS>
</REV>
```

Esempio dati output:
```
             <tiapit:atTime>
                  <tiapit:TimeInterval rdf:about="https://w3id.org/arco/resource/TimeInterval/-xviii">
                    <rdfs:label> - XVIII</rdfs:label>
                    <l0:name> - XVIII</l0:name>
                    <tiapit:time> - XVIII</tiapit:time>
                  </tiapit:TimeInterval>
                </tiapit:atTime>
                <arco-cd:specificTime>
                  <tiapit:TimeInterval rdf:about="https://w3id.org/arco/resource/TimeInterval/1786">
                    <rdfs:label>1786 - </rdfs:label>
                    <l0:name>1786 - </l0:name>
                    <arco-arco:startTime>1786</arco-arco:startTime>
                    <arco-arco:endTime></arco-arco:endTime>
                  </tiapit:TimeInterval>
                </arco-cd:specificTime>
```

**Descrivere come riprodurre il problema**
Esempio si record della scheda A con estremi cronologici di tipo diverso
https://drive.google.com/file/d/1ODGYrzC-u5HxT8OT_VvliCy2O9HqKCAl/view?usp=sharing

**Comportamento atteso**
Che si considerino come estremi cronologici di uno stesso arco temporale i casi in cui i due estremi sono di diverso tipo.

**Informazioni aggiuntive**
Almeno nei casi della Regione Lombardia, ci sono molti casi in cui un estremo è conosciuto in maniera precisa (indicato con l'anno) e l'altro estremo non è preciso (indicato con il secolo).
Nelle norme di compilazione della Scheda A 3.0 non ho trovato indicazione che dicano che questo uso non è consentito, quindi mi aspetterei che questo tipo di situazione si possa rappresentare anche negli Rdf.

**Comment by margherita-porena** [comment]
Ho modificato le regole per la cronologia dei beni architettonici, dal momento che per gli altri beni (che non usano i campi RE, ma i campi DT), non mi pare che si possa creare questo problema: in queste altre schede il riferimento al secolo è esplicitato in un unico campo (DTZG) e non si fa riferimento al fato che sia un estremo recente o remoto.
Commit: 25464b3
