### ISSUE TITLE
Schede NU - core:description mai compilato

### ISSUE THREAD

**Issue by ICCD-MiBACT** [ICCD-MiBACT/ArCo#119]
la proprietà core:description non è mai presente nelle schede NU mentre è presente dc:description.
Si potrebbe compilare core:description con le stesse regole che si usano per compilare dc:description?
Vedi ad esempio
https://dati.beniculturali.it/lodview-arco/resource/NumismaticProperty/1300213083.html

**Comment by margherita-porena** [comment]
The issue has been solved with commit 04aa20d
