### ISSUE TITLE
Modellazione paragrafi delle schede BNB e produzione dei LOD

### ISSUE THREAD

**Issue by ICCD-MiBACT** [ICCD-MiBACT/ArCo#126]
Prevedere la modellazione ontologica di tutti i campi del seguente paragrafo:

SB - SISTEMATICA-BOTANICA

Controllare la presenza di tutti i campi di OG - OGGETTO

Una volta modellati, produrre i LOD dalle schede di Catalogo

**Comment by margherita-porena** [comment]
Il dominio dei beni botanici è già stato modellato e i dati pubblicati nella release di giugno
