### ISSUE TITLE
Difficoltà a interpretare i dati: AUTORE

### ISSUE THREAD

**Issue by ICCD-MiBACT** [ICCD-MiBACT/ArCo#128]
Se guardo questa risorsa:
https://dati.beniculturali.it/lodview-arco/resource/Agent/0367598802c7edb9472bdd210b58eeb4.html
non capisco quante siano le risorse "bene culturale" in ArCo collegate a questo autore (che è Leonardo da Vinci?
Sono 11, 59 o 124?
Guardate le RELAZIONI INVERSE.
è a-cd:hasAttributedAuthor di 11 risorse
è <http://data.cochrane.org/ontologies/pico/author> di 59 risorse
è a-cd:hasAuthor di 124 risorse
è dc:creator di 59 risorse

**Comment by margherita-porena** [comment]
Le relazioni dc e pico sono state allineate con la relazione hasAuthor. La relazione hasAttributedAuthor viene utilizzata per collegare l'autore alla situazione di AuthorshipAttribution (non è un collegamento diretto tra l'opera e l'autore).
Commit: 75239f3
