### ISSUE TITLE
Allineamento con i Luoghi della Cultura

### ISSUE THREAD

**Issue by giorgiobevilacqua** [ICCD-MiBACT/ArCo#13]
Dove possibile sarebbe utile allineare le entità cis:Site con i Luoghi della Cultura esposti su dati.beniculturali.it/sparql

**Comment by giorgiobevilacqua** [comment]
Risolvendo problemi di data cleaning di questo tipo:
label dei cis:Site con sede a Cagliari:

PREFIX arco: <http://www.w3id.org/arco/core/>
PREFIX cis: <http://dati.beniculturali.it/cis/>
PREFIX locgeoamm: <http://www.w3id.org/arco/locgeoamm/>
SELECT distinct ?siteLabel
WHERE{
?entity locgeoamm:isInSite ?site .
?site rdfs:label ?siteLabel .
?site cis:siteAddress ?siteAddress .
?siteAddress <https://w3id.org/italia/onto/CLV/hasCity> <https://w3id.org/arco/resource/City/cagliari>
}

**Comment by ICCD-MiBACT** [comment]
Importante risolvere quanto prima questa issue

**Comment by luigi-asprino** [comment]
Ciao, 

avevo programmato di farlo insieme alla conclusione della issue #68, ma visto che questa issue è aperta da tanto tempo mi sembra giusto risolverla quanto prima.

Allora, spiego quello che ho fatto.
Ho usato [LIMES](http://aksw.org/Projects/LIMES.html) per la scoperta dei link (sameAs) tra i ``cis:Site'' dei Luoghi della Cultura e quelli di ArCo.
Le strategie che ho implementato per il linking sono state fondamentalmente 2:
1) Linking usando label e città in cui si trovano i site.
2) Linking usando il toponimo del site.
Ovviamente le due  euristiche hanno affidabilità diversa per questo penso che siamo meglio mantenere separati i link provenienti dalle due strategie, lasciando così agli utenti la scelta di quale tra le due strategie adottare.

Per quanto riguarda l'applicazione della prima euristica trovate i risultati [qui](http://etna.istc.cnr.it/arco-data/linking/cis_site_match_label.nt).
Mi sembra che non interessi i dati generati da ArCo, ma di fatto vengono allineati i site dei Luoghi della Cultura con altri ``cis:Site'' presenti sullo SPARQL endpoint MiBACT (penso che siano contenitori fisici dell'ICCD e del SAN).
Anche se non interessa direttamente ArCo, penso che questo linking sia utile lo stesso.

Per quanto riguarda l'applicazione della seconda euristica trovate i risultati [qui](http://etna.istc.cnr.it/arco-data/linking/cis_site_match_toponym.nt).
Qui invece sono stati allineati molti site di ArCo e dei Luoghi della Cultura.

Entrambi i linking verrano inclusi nella prossima release di ArCo (mantenendoli sempre su diversi Named  Graph).

Per ora chiudo la issue, ma se ci sono altri suggerimenti su come arricchire o raffinare i risultati vi prego di farli presente.

Un saluto,
Luigi
