### ISSUE TITLE
Produzione Contenitori fisici, allineamento coi CF di ICCD e coi dati del DBUnico

### ISSUE THREAD

**Issue by ICCD-MiBACT** [ICCD-MiBACT/ArCo#130]
Ho bisogno di capire come viene gestita la produzione dei Contenitori fisici in ArCo e l'aggancio ai luoghi della Cultura nel DBUNico.
In particolare chiedo:
1) Dalle schede di catalogo voi generate automaticamente dei contenitori fisici a partire dai dati di localizzazione? che dati usate?
2) Se ho il Contenitore Fisico (come scheda) da SIGEC come fate ad agganciarlo a quello predisposto da voi a partire dai dati di localizzazione? E' fondamentale che ci sia coerenza
3) Quali contenitori fisici sono agganciati al DBUnico? Quelli prodotti da voi o quelli prodotti da SIGEC o entrambe?

**Dal 23/11/2020 in harvesting del Catalogo verranno aggiunti alle schede altri 2 tag <idContenitoreFisico>  e <idContenitoreGiuridico> nel quale ci saranno i keycode dei contenitori. Sulla base di questi identificativi dovranno essere creati i collegamenti tra i beni e i contenitori. Solo se questi identificativi non ci sono, viene tentato tentato l'aggancio ai Site creati a partire dai campi delle schede,**

**Comment by ICCD-MiBACT** [comment]
in harvesting OAI, nei nuovi record pubblicati, è visibile il nuovo aggancio ai contenitori fisici (campo in più <idContenitoreGiuridico>) che dal 23 novembre verrà esteso a tutte le schede pubblicate in OAI.

Questo significa che laddove è presente il campo (ovvero la scheda è agganciata esplicitamente in SIGEC ad un contenitore) NON andrà più messa in atto la procedura che prevede la creazione automatica di contenitori tramite Address e l'aggancio ad essi delle schede MA andrà previsto l'aggancio alla scheda contenitore di SIGEC.

Laddove <idContenitoreGiuridico> non è presente invece, e si tratta sempre di beni mobili, va lasciata la procedura attuale.






Ad esempio questa scheda 

http://catalogo.beniculturali.it/oaitarget/OAIHandler?verb=GetRecord&metadataPrefix=oai_dc&identifier=oai:oaicat.iccd.org:@ICCD8548954@/xml



si collega a questa 



http://catalogo.beniculturali.it/oaitarget/OAIHandler?verb=GetRecord&metadataPrefix=oai_dc&identifier=oai:oaicat.iccd.org:@ICCD13329725@/xml/contenitori_fisici

**Comment by margherita-porena** [comment]
The issue has been closed
