### ISSUE TITLE
Problema schede A - relazione bene componente / bene complesso

### ISSUE THREAD

**Issue by ICCD-MiBACT** [ICCD-MiBACT/ArCo#132]
RDFsizer: la relazione bene complesso / bene componente è espressa non tramite URL ma tramite testo e va corretta. 
Vedi per esempio
https://dati.beniculturali.it/lodview-arco/resource/ArchitecturalOrLandscapeHeritage/1100222450-bene-componente.html

Inoltre se si vede la query di sotto, si nota come per molte schede manca il collegamento:

https://dati.beniculturali.it/sparql?default-graph-uri=&query=select+distinct+%3FURI+%3FrelatedURIComponentOf+where%0D%0A%7B%0D%0A%3FURI+a+%3Chttps%3A%2F%2Fw3id.org%2Farco%2Fontology%2Farco%2FArchitecturalOrLandscapeHeritage%3E%3B+rdfs%3Alabel+%3FlabelBene.%0D%0AFILTER+%28+lang%28%3FlabelBene%29+%3D+%22it%22+%29%0D%0A%3FURI+%3Chttps%3A%2F%2Fw3id.org%2Farco%2Fontology%2Farco%2FisCulturalPropertyComponentOf%3E+%3FrelatedURIComponentOf.%0D%0A%7D&format=text%2Fhtml&timeout=0&debug=on

**Comment by margherita-porena** [comment]
The issue has been solved with commit 64e7fa4
