### ISSUE TITLE
scheda FF - OGTC e MTI

### ISSUE THREAD

**Issue by fguernaccini** [ICCD-MiBACT/ArCo#133]
Il campo OGTC (consistenza /composizione) non è mappato su un campo specifico (o lo è ma non lo trovo perché non è segnalato nell'iccdNormTag?), l'informazione infatti è riportata, insieme ad altri campi, in rdfs:comment.
Es. https://w3id.org/arco/resource/PhotographicHeritage/1201254148
http://catalogo.beniculturali.it/sigecSSU_FE/schedaCompleta.action?keycode=ICCD13074493

Il campo MTI non risulta mappato

**Comment by margherita-porena** [comment]
Per le schede FF il campo OGTC è modellato come core:description, dal momento che è un campo a testo libero che consente la descrizione fisica/quantitativa del bene oggetto della catalogazione.
Il campo MTI corrisponde alla dp arco-cd:methodOfInterventionAndDigitization.
Commit: 26c6b04
