### ISSUE TITLE
SCHEDA E - RP

### ISSUE THREAD

**Issue by fguernaccini** [ICCD-MiBACT/ArCo#135]
Non sono pubblicati LOD per le seguenti informazioni
RP-Reperimento, SPR-Specifiche di Reperimento (SPRN: Nome Raccoglitore-SPRD:Data del reperimento)

**Comment by margherita-porena** [comment]
Ciao Fabiana,
dato che la scheda è obsoleta, su consiglio di ICCD è stato deciso di non creare regole di trasformazione per i campi che non sono mai stati compilati dai catalogatori (tra cui proprio i campi da te indicati) e per i quali, quindi, non ci sarebbero comunque dati.
