### ISSUE TITLE
Errore produzione dati/ontologia

### ISSUE THREAD

**Issue by fguernaccini** [ICCD-MiBACT/ArCo#136]
La proprietà hasUse è formalizzata nella context-description ontology, ma nei beni architettonici la proprietà è stata associata alla denotative-description ontology: https://dati.beniculturali.it/lodview-arco/resource/ArchitecturalOrLandscapeHeritage/0800263883.html

**Comment by margherita-porena** [comment]
The issue has been solved with commit 6602d36
