### ISSUE TITLE
SCHEDA MI - campo SGTS

### ISSUE THREAD

**Issue by fguernaccini** [ICCD-MiBACT/ArCo#137]
Necessità di modellazione del campo SGTS - Titolo della serie di appartenenza
es. https://w3id.org/arco/resource/HistoricOrArtisticProperty/1200268657-55
http://catalogo.beniculturali.it/sigecSSU_FE/schedaCompleta.action?keycode=ICCD11591082

**Comment by margherita-porena** [comment]
The issue has been solved with commit ad483fc
