### ISSUE TITLE
Modellazione paragrafi delle schede BNB e produzione dei LOD

### ISSUE THREAD

**Issue by fguernaccini** [ICCD-MiBACT/ArCo#138]
Non risultano mappate le sezioni LR e SB

**Comment by margherita-porena** [comment]
Le sezioni LR e SB sono state modellate nel modulo ontologico movable-property e i Lod sono stati prodotti.

**Comment by fguernaccini** [comment]
Ciao Margherita, posso chiederti degli esempi per favore?
Per LR, non trovo modellati questi campi LRVT: LRVK , LRVS, LRVR, LRVC (LRVP), LRIE
Per SB, ho trovato modellato SBSN e SBSF (non SBSC) ma non trovo dati prodotti.
Grazie!

**Comment by margherita-porena** [comment]
Ciao Fabiana,
i campi relativi a LR sono considerati come Feature (ho utilizzato lo stesso modello usato per il paragrafo UTL delle schede BDM v. 1 e 2). 
Il campo SBSC è una Bibliografia, che è collegata alla classe core:ClassificationInTime tramite la proprietà cd:hasBibliography.
In generale, non trovi alcuni dati prodotti perché ho modificato alcune regole di trasformazione (principalmente relative ai prefissi di classi e proprietà, che inizialmente facevano parte del modulo context-description, ma che poi ho spostato nel modulo movable-property) e i dati non sono ancora stati aggiornati secondo le nuove regole.
Se vuoi posso darti la query per trovare i dati ora e la query da usare quando i dati saranno aggiornati

**Comment by fguernaccini** [comment]
Ciao Margherita, magari certo, mi farebbero comodo entrambe, sia per trovarli ora che nel momento dell'aggiornamento!
Ti ringrazio
