### ISSUE TITLE
collegamento delle entità a-dd:Measurement

### ISSUE THREAD

**Issue by oibaf** [ICCD-MiBACT/ArCo#139]
**Indicare quali parti del progetto sono coinvolte nel bug: ontologia, knowledge graph, rdfizer**

rdfizer

**Descrivere il problema**

il riferimento a entità a-dd:Measurement in a-dd:MeasurementCollection non è sempre consistente

**Descrivere come riprodurre il problema**

ad esempio

[ICCD2908228](https://w3id.org/arco/resource/DemoEthnoAnthropologicalHeritage/1100184687)

https://w3id.org/arco/resource/Measurement/1100184687-1-length
https://w3id.org/arco/resource/Measurement/1100184687-1-width

https://w3id.org/arco/resource/Measurement/1100184687-3-length
https://w3id.org/arco/resource/Measurement/1100184687-2-width

[ICCD2254714](https://w3id.org/arco/resource/HistoricOrArtisticProperty/0100142360)

https://w3id.org/arco/resource/Measurement/0100142360-1-diameter
https://w3id.org/arco/resource/Measurement/0100142360-2-diameter

[ICCD2254733](https://w3id.org/arco/resource/HistoricOrArtisticProperty/0100142368)

https://w3id.org/arco/resource/Measurement/0100142368-1-depth
https://w3id.org/arco/resource/Measurement/0100142368-1-width

https://w3id.org/arco/resource/Measurement/0100142368-3-depth
https://w3id.org/arco/resource/Measurement/0100142368-2-width

**Comportamento atteso**

riferimenti consistenti

**Informazioni aggiuntive**

**Comment by oibaf** [comment]
almeno nei casi indicati il problema si presenta in v1.1-pr2-dev e non in master

**Comment by margherita-porena** [comment]
The issue has been closed with commit 7dbbcb6
