### ISSUE TITLE
produzione rdf

### ISSUE THREAD

**Issue by oibaf** [ICCD-MiBACT/ArCo#140]
**Indicare quali parti del progetto sono coinvolte nel bug: ontologia, knowledge graph, rdfizer**

rdfizer

**Descrivere il problema**

la trasformazione di alcuni record produce dati rdf non validi

**Descrivere come riprodurre il problema**

ad esempio ICCD11761045

genera la tripla nt
```
<https://w3id.org/arco/resource/NaturalHeritage/2000219529> <https://w3id.org/arco/ontology/core/isClassifiedBy> <https://w3id.org/arco/resource/BiologicalTaxon/" />
```
probabilmente a causa di un [refuso](https://github.com/ICCD-MiBACT/ArCo/blob/9348af7488f6e229e3871d15fdc78881b429f1da/ArCo-release/rdfizer/src/main/resources/META-INF/xslt/BNB.xslt#L355) nella trasformazione

**Comportamento atteso**

produzione di rdf valido

**Informazioni aggiuntive**
Fornire qualsiasi informazioni aggiuntiva che possa aiutare nella interpretazione e correzione del problema.

**Comment by margherita-porena** [comment]
Ho fatto una prova con la scheda che hai indicato e non mi riproduce l'errore (questa è la tripla prodotta:
<https://w3id.org/arco/resource/NaturalHeritage/2000219529> <https://w3id.org/arco/ontology/movable-property/isClassifiedByOriginalTaxon> <https://w3id.org/arco/resource/BiologicalTaxon/callitriche-callitriche-platycarpa> )
Potresti dirmi quale versione dell'xslt state utilizzando?
Comunque vedendo il risultato di questa trasformazione ho notato che c'è un problema con i dati di origine (a volte viene ripetuta l'informazione del genere all'interno del campo relativo alla specie - come in questo caso - e a volte no, e questo produce duplicazioni dello stesso taxon), ma sto provvedendo a pulire i dati.

**Comment by oibaf** [comment]
ho eseguito la trasformazione con la versione attuale, è vero, viene prodotta la tripla che indichi ma poco oltre a seguire compaiono anche queste due righe
```
<https://w3id.org/arco/resource/NaturalHeritage/2000219529> <https://w3id.org/arco/ontology/core/isClassifiedBy> <https://w3id.org/arco/resource/BiologicalTaxon/" />
				> .
```
che causano l'errore nel parser, comunque se guardi in fondo alla riga 355 della trasformazione trovi dopo la chiusura del tag questa sequenza di caratteri `" />`, chiaramente un refuso, e dovrebbe essere sufficiente rimuoverla

grazie!

**Comment by margherita-porena** [comment]
Grazie, non avevo visto il refuso!
Ho risolto con il commit af09eba
