### ISSUE TITLE
URI Prefix

### ISSUE THREAD

**Issue by luigi-asprino** [ICCD-MiBACT/ArCo#141]
**Indicare quale componente del progetto si riferisce la richiesta**

rdfizer

**La richiesta è relativo ad un problema?**

Le URI generate da rdfizer hanno sempre lo stesso prefisso ``https://w3id.org/arco/resource/``

**Descrivi la soluzione che ti piacerebbe avere**

Vorrei che le URI generate da RDFizer avessero un prefisso parametrizzabile

**Informazioni aggiuntive**

Utile per permettere il riuso di RDFizer da parte di esterni

**Comment by ICCD-MiBACT** [comment]
Questa modifica è urgente

**Comment by luigi-asprino** [comment]
Addressed with commit 180528877327aaed806a8596274c9b5440bd9c5a
