### ISSUE TITLE
LInk alla scheda nel sistema di provenienza

### ISSUE THREAD

**Issue by ICCD-MiBACT** [ICCD-MiBACT/ArCo#142]
Abbiamo previsto il link alla scheda di catalogo completa in formato PDF anche nei nostri LOD.
Ora dobbiamo prevedere il link alla scheda (in qualunque formato, anche html) nel sistema di provenienza.
Il Link alla scheda può essere recuperato come dc:source.
tale link può essere reso parametrico, ad esempio prevedendo nell'XML di origine un tag <URL> che può essere il prefisso della URL che si mette nel campo dc:source per mettere il link alle schede in PDF della regione. 
Nel caso della Lombardia questa URL sarebbe http://www.lombardiabeniculturali.it/opere-arte/schede-complete/

In questo momento (come Alessandro Chiaretti spiegava nella segnalazione 111 (https://github.com/ICCD-MiBACT/ArCo/issues/111), nei dati della Lombardia si crea un link con dc:source a Sigec però ovviamente in Sigec non esiste quel record (esempio <dc:source rdf:resource="http://www.catalogo.beniculturali.it/sigecSSU_FE/dettaglioScheda.action?keycode=P0110-00001"/>). I
l link corretto sarebbe infatti http://www.lombardiabeniculturali.it/opere-arte/schede-complete/P0110-00001

**Comment by ICCD-MiBACT** [comment]
Questa modifica è urgente

**Comment by luigi-asprino** [comment]
Addressed with issue ed00d36ad9b20836d4abc55d90d4e669f804d066
