### ISSUE TITLE
Ancora problemi con gli Address

### ISSUE THREAD

**Issue by ICCD-MiBACT** [ICCD-MiBACT/ArCo#143]
Se vedete questa risorsa
https://dati.beniculturali.it/lodview-arco/resource/Address/baf8c807fbde64045fa67254dafd3e9f.html

nella label e in hasRegion compaiono sia Lombardia che Toscana.
Come può essere? Il dato giusto è Toscana

Occorre verificare la procedura che genera gli address per non ripetere l'errore.

**Comment by margherita-porena** [comment]
The issue has been solved with commit 7d8e03d
