### ISSUE TITLE
Allineamenti non sono nell'endpoint

### ISSUE THREAD

**Issue by Christian-Nja** [ICCD-MiBACT/ArCo#144]
**Sparql endpoint**: dati.beniculturali.it/sparql
**Query**:
```
SELECT ?subProp WHERE {
    ?subProp rdfs:subPropertyOf <http://www.ontologydesignpatterns.org/ont/dul/DUL.owl#hasSetting> .
}
```
Come si vede dall [file di allineamento core](https://github.com/ICCD-MiBACT/ArCo/blob/7a167ac617cb9ac38c4573a9026c8cb41c82919b/ArCo-release/ontologie/core/core-aligns.owl#L133
) `:hasSetting` ha una sottoproprietà

**Comment by oibaf** [comment]
ontologie e allineamenti sono stati aggiornati il 3 novembre

**Comment by Christian-Nja** [comment]
La query adesso funziona!
