### ISSUE TITLE
Caratteri in URI

### ISSUE THREAD

**Issue by alechiaretti** [ICCD-MiBACT/ArCo#145]
**Indicare quali parti del progetto sono coinvolte nel bug: ontologia, knowledge graph, rdfizer**
rdfizer

**Descrivere il problema**
Nella composizione delle URI non vengono sostituiti caratteri speciali presenti nei dati di input.

**Descrivere come riprodurre il problema**
Esempio di dati di input (è presente il campo ACC e non NCTN) https://drive.google.com/file/d/1CcohTWsOTjEkcF1-wp81J1HHf4SQAtT3/view?usp=sharing
Risultato con rdfizer attuale https://w3id.org/arco/resource/ArchitecturalOrLandscapeHeritage/1A050-00323/R03

**Comportamento atteso**
Che nelle URI si sostiuiscano alcuni caratteri "speciali", con qualche caratteri accettati.

**Informazioni aggiuntive**
Nelle risorse in cui non c'è il campo NCTN, si usa il campo ACC per creare le URI. Il valore di ACC di solito contiene anche i caratteri "/" e " ". Anche se non si tratta di caratteri che danno problemi, mi sembra una buona regola sostituirli con un altro carattere (per esempio "_").
La norma che descrive il campo ACC dice: "Il codice identificativo (numerico o alfanumerico) dovrà essere seguito dalla specifica dell’ente cui si riferisce, separato da quest’ultimo da una barra, seguita da uno spazio".

**Comment by margherita-porena** [comment]
The issue has been solved with commit 2cd42e6
