### ISSUE TITLE
missing domain and/or range

### ISSUE THREAD

**Issue by Valentina10** [ICCD-MiBACT/ArCo#147]
**Indicate which part of the project the bug concerns: ontology, knowledge graph, rdfizer**
ontology

**Describe the bug**
some properties miss rdfs:domain and/or range.

**To Reproduce**
SELECT DISTINCT ?prop
WHERE {{?prop a owl:ObjectProperty 
FILTER NOT EXISTS {?prop rdfs:domain ?domain}}
UNION
{?prop a owl:DatatypeProperty 
FILTER NOT EXISTS {?prop rdfs:domain ?domain}}
UNION
{?prop a owl:DatatypeProperty 
FILTER NOT EXISTS {?prop rdfs:range ?range}}
UNION
{?prop a owl:ObjectProperty 
FILTER NOT EXISTS {?prop rdfs:range ?range}}
FILTER(regex(str(?prop), '^https://w3id.org/arco/'))
}

**Expected behavior**
all properties have domain and range

**Additional context**
In some cases, they seem duplicates of other (annotated) properties. 
E.g. a-cd:isMemberOfCollection VS a-cd:isMemberOfCollectionOf
E.g. a-cd:isMemberOfPhotographicSeries VS a-cd:isMemberOfPhotographicSeriesIn

**Comment by margherita-porena** [comment]
The issue has been closed with commit d8cfe22
