### ISSUE TITLE
AU/AUT AUTA not AUTN

### ISSUE THREAD

**Issue by oibaf** [ICCD-MiBACT/ArCo#148]
**Indicare quali parti del progetto sono coinvolte nel bug: ontologia, knowledge graph, rdfizer**

rdfizer

**Descrivere il problema**

schede con elemento AU/AUT/AUTA ma senza AU/AUT/AUTN generano una eccezione e non completano la trasformazione verso rdf  (circa 1700 casi)

Type error at char 38 in xsl:value-of/@select on line 28890 column 78
  XPTY0004: An empty sequence is not allowed as the first argument of arcofy()
net.sf.saxon.s9api.SaxonApiException: An empty sequence is not allowed as the first argument of arcofy()
        at net.sf.saxon.s9api.XsltTransformer.transform(XsltTransformer.java:606)
        at it.cnr.istc.stlab.arco.Converter.convert(Converter.java:267)

(arco.xslt)

**Descrivere come riprodurre il problema**

ad esempio ICCD10433671

**Comportamento atteso**

la trasformazione va a buon fine

**Comment by margherita-porena** [comment]
The issue has been solved with commit 0afe94a
