### ISSUE TITLE
collegamento al bene bibliografie relative al taxon biologico

### ISSUE THREAD

**Issue by oibaf** [ICCD-MiBACT/ArCo#149]
**Indicare quali parti del progetto sono coinvolte nel bug: ontologia, knowledge graph, rdfizer**

rdfizer

**Descrivere il problema**

alcune bibliografie non risultano collegate al bene di riferimento (se non per la descrizione testuale)

**Descrivere come riprodurre il problema**

 ad esempio
  ICCD11876283 https://w3id.org/arco/resource/NaturalHeritage/2000219727
   https://w3id.org/arco/resource/Bibliography/2000219727-biological-taxon-bibliography

  ICCD11876261https://w3id.org/arco/resource/NaturalHeritage/2000219726
   https://w3id.org/arco/resource/Bibliography/2000219726-biological-taxon-bibliography

**Comportamento atteso**

 presenza di una proprietà che permetta il collegamento del bene alla risorsa

**Comment by margherita-porena** [comment]
The issue has been closed with commit 97160d8
