### ISSUE TITLE
collegamento al bene collezioni di particelle catastali storiche

### ISSUE THREAD

**Issue by oibaf** [ICCD-MiBACT/ArCo#150]
**Indicare quali parti del progetto sono coinvolte nel bug: ontologia, knowledge graph, rdfizer**

rdfizer

**Descrivere il problema**

alcune delle entità https://w3id.org/arco/ontology/location/CadastralUnitCollection non risultano collegate al bene (se non per la descrizione testuale)

**Descrivere come riprodurre il problema**

ad esempio

 ICCD13931292 https://w3id.org/arco/resource/ArchitecturalOrLandscapeHeritage/0500038813
  https://w3id.org/arco/resource/CadastralUnitCollection/0500038813-historical-2
  https://w3id.org/arco/resource/CadastralUnitCollection/0500038813-historical-3

 ICCD13930914 https://w3id.org/arco/resource/ArchitecturalOrLandscapeHeritage/0500038810
  https://w3id.org/arco/resource/CadastralUnitCollection/0500038810-historical-2
  https://w3id.org/arco/resource/CadastralUnitCollection/0500038810-historical-3

**Comportamento atteso**

presenza di una proprietà che permetta il collegamento del bene alla risorsa

**Comment by margherita-porena** [comment]
The issue has been solved with commit 950f75f
