### ISSUE TITLE
collegamento al bene immovable-property/Roof

### ISSUE THREAD

**Issue by oibaf** [ICCD-MiBACT/ArCo#151]
**Indicare quali parti del progetto sono coinvolte nel bug: ontologia, knowledge graph, rdfizer**

rdfizer

**Descrivere il problema**

assenza di collegamento al bene per entità https://w3id.org/arco/ontology/immovable-property/Roof (se non per la descrizione testuale)

**Descrivere come riprodurre il problema**

ad esempio: 

 ICCD11444124 https://w3id.org/arco/resource/ArchitecturalOrLandscapeHeritage/1800027746
  https://w3id.org/arco/resource/RoofPart/1800027746-part-parte-della-copertura

 ICCD14626677 https://w3id.org/arco/resource/ArchitecturalOrLandscapeHeritage/1500178627A
  https://w3id.org/arco/resource/Roof/1500178627A-e5098cbb5a8eab24b1ee10827f4c1fdb

**Comportamento atteso**

collegamento della risorsa al bene

**Comment by margherita-porena** [comment]
The issue has been solved with commit 195b3b8
