### ISSUE TITLE
implementazione risorse

### ISSUE THREAD

**Issue by oibaf** [ICCD-MiBACT/ArCo#155]
**Indicare quali parti del progetto sono coinvolte nel bug: ontologia, knowledge graph, rdfizer**

rdfizer

**Descrivere il problema**

l'implementazione delle risorse negli esempi indicati (referenziate da altre entità del bene) risulta incompleta o assente

**Descrivere come riprodurre il problema**

ad esempio:

 ICCD12200473 https://w3id.org/arco/resource/HistoricOrArtisticProperty/0100211807-0
  https://w3id.org/arco/resource/CulturalEntityTechnicalStatus/0100211807-0

 ICCD13812136 https://w3id.org/arco/resource/ArchaeologicalProperty/1201339454
  https://w3id.org/arco/resource/RelatedWorkSituation/1201339454-related-cultural-property-2-2

 ICCD13814307 https://w3id.org/arco/resource/DemoEthnoAnthropologicalHeritage/0500694715
  https://w3id.org/arco/resource/Measurement/0500694715-3-

 ICCD13231475 https://w3id.org/arco/resource/PhotographicHeritage/0800635803-430
  https://w3id.org/arco/resource/PreparatoryOrFinalWork/0800635803-430-negativo-collodio-vetro

 ICCD14436923 https://w3id.org/arco/resource/ArchitecturalOrLandscapeHeritage/1500261606A
  https://w3id.org/arco/resource/CulturalPropertyPart/1500261606A-part-intero-bene

**Comportamento atteso**

 la corretta implementazione della risorsa (o la correzione del riferimento)

**Comment by margherita-porena** [comment]
The issue has been solved with the commits mentioned in the comments before.
