### ISSUE TITLE
riferimenti a entità indefinite

### ISSUE THREAD

**Issue by oibaf** [ICCD-MiBACT/ArCo#156]
**Indicare quali parti del progetto sono coinvolte nel bug: ontologia, knowledge graph, rdfizer**

rdfizer

**Descrivere il problema**

nei dati rdf sono presenti riferimenti a entità indefinite (protocollo file:)

**Descrivere come riprodurre il problema**

il valore dell'identificativo della risorsa dipende dall'ambiente di produzione dei dati e coincide con la directory in cui viene eseguito il processo di trasformazione (sul server ArCo `<file:///root/ArCo/ArCo-release/rdfizer/>`), le entità coinvolte possono quindi essere isolate con una [interrogazione](https://dati.beniculturali.it/sparql?query=select+distinct%3Fs%3Fp%7Bgraph%3Chttps%3A%2F%2Fw3id.org%2Farco%2Fdata%3E%7B%3Fs%3Fp%3Cfile%3A%2F%2F%2Fc%3A%2Fopt%2Fmaas%2Fbuild%2Fprocedure_ICCD%2Foai%2F%3E%7D%7Dorder+by%3Fs%3Fp)

`select distinct?s?p{?s?p<file://directory del processo di trasformazione>}`

ma esiste anche il [soggetto](https://dati.beniculturali.it/sparql?query=select%3Fp%3Fo%7B%3Cfile%3A%2F%2F%2Fc%3A%2Fopt%2Fmaas%2Fbuild%2Fprocedure_ICCD%2Foai%2F%3E%3Fp%3Fo%7D)

questi alcuni dei casi rappresentativi delle [propietà](https://dati.beniculturali.it/sparql?query=select+sample%28%3Fs%29as%3Fsample%3Fp%7Bgraph%3Chttps%3A%2F%2Fw3id.org%2Farco%2Fdata%3E%7B%3Fs%3Fp%3Cfile%3A%2F%2F%2Fc%3A%2Fopt%2Fmaas%2Fbuild%2Fprocedure_ICCD%2Foai%2F%3E%7D%7Dgroup+by%3Fp) coinvolte

ICCD3714421 ICCD10598902 ICCD12310424 ICCD9702712 ICCD11400507 ICCD11874371 ICCD13831921 ICCD11121090 ICCD12117681 ICCD11079121 ICCD11684227

context-description/involvesRelatedWork
context-description/hasFindingLocation
context-description/hasPreviousLocation
context-description/hasUrbanPlanningEnvironmentalRelationWith
context-description/isLocatedIn
context-description/isReusedBy
context-description/hasCreationLocation
denotative-description/hasCulturalPropertyType
context-description/isInvolvedIn
location/atLocation
context-description/isSubjectOf

**Comportamento atteso**

le entità indefinite vengono risolte

i dati statici (il file db) letti dalla trasformazione andrebbero aggiornati in modo incrementale parallelamente al processo di sincronizzazione dei contenuti con il repository OAI (nel contesto dati.beniculturali.it dei collegamenti riportati nella descrizione)

**Informazioni aggiuntive**

parte delle cause vanno cercate probabilmente nel disallineamento dei dati statici nei quali non trovano riscontro le nuove schede, ma sono presenti anche casi non pertinenti, comunque la gran parte dei casi è presente anche nella [versione statica sul server ArCo](http://arco.istc.cnr.it/arco-1.1/virtuoso/sparql?query=%23select+distinct%3Fs%3Fo%7Bgraph%3Chttps%3A%2F%2Fw3id.org%2Farco%2Fdata%3E%7B%3Fs%3Chttps%3A%2F%2Fw3id.org%2Farco%2Fontology%2Fcontext-description%2FhasFindingLocation%3E%3Fo+filter%28strstarts%28str%28%3Fo%29%2C%22file%22%29%29%7D%7D%0D%0Aselect+sample%28%3Fs%29as%3Fsample%3Fp+count%28distinct%3Fs%29as%3Fcount%7Bgraph%3Chttps%3A%2F%2Fw3id.org%2Farco%2Fdata%3E%7B%3Fs%3Fp%3Cfile%3A%2F%2F%2Froot%2FArCo%2FArCo-release%2Frdfizer%2F%3E%7D%7Dgroup+by%3Fp+order+by+desc%28%3Fcount%29)

**Comment by margherita-porena** [comment]
The issue has been closed with commits listed above
