### ISSUE TITLE
URI dei CIS riferiti a molti (troppi) site

### ISSUE THREAD

**Issue by ICCD-MiBACT** [ICCD-MiBACT/ArCo#158]
Controllare perchè https://dati.beniculturali.it/lodview-arco/resource/CulturalInstituteOrSite/cba87668e0d68314ea021668d90513b9.html ha tanti Site. Il problema è grave e ripetuto perchè la URI del CIS non tiene conto del campo LDCN (=denominazione). Se non è compilato LDCN bisogna considerare LDCC (=complesso di appartenenza) in modo da poter disambiguare.

**Comment by margherita-porena** [comment]
La issue è stata risolta con il commit d97d43b.
Volevo sapere se è necessario creare un collegamento con la precedente URI dei CIS.

**Comment by chiaraven** [comment]
penso che è necessario mantenere il collegamento
Chiara Veninata


Il giorno ven 13 nov 2020 alle ore 11:16 margherita-porena <
notifications@github.com> ha scritto:
