### ISSUE TITLE
Campo MTC ripetibile

### ISSUE THREAD

**Issue by ICCD-MiBACT** [ICCD-MiBACT/ArCo#160]
La trasformazione XSLT non considera che MTC può essere ripetibile.
Vedi ad esempio una scheda RA http://catalogo.beniculturali.it/sigecSSU_FE/schedaCompleta.action?keycode=ICCD10979899
e la corrispondente "scheda" espressa in  RDF
https://dati.beniculturali.it/lodview-arco/resource/ArchaeologicalProperty/1200586398.html

**Comment by margherita-porena** [comment]
The issue has been solved with commit 4efbc80
