### ISSUE TITLE
Difformità nella modellazione delle misure 

### ISSUE THREAD

**Issue by ICCD-MiBACT** [ICCD-MiBACT/ArCo#161]
C'è una differenza nella restituzione dei valori delle misure tra a-dd:hasMeasurementCollection e dc:format.
vedi ad esempio scheda https://dati.beniculturali.it/resource/ArchaeologicalProperty/1200586398

dc:format --> riporta solo l'altezza (MISA)

a-dd:hasMeasurementCollection riporta solo le altre misure (MISV)

L'origine dei dati è visibile qui http://catalogo.beniculturali.it/sigecSSU_FE/schedaCompleta.action?keycode=ICCD10979899

Richiesta: comportamento uniforme tra dc:format  e a-dd:hasMeasurementCollection  con tutte le misure del bene

**Comment by margherita-porena** [comment]
Il link alla risorsa indicata non funziona. Provando la navigazione della risorsa da questo link https://w3id.org/arco/resource/ArchaeologicalProperty/1200586398 non vedo questa differenza (entrambe le proprietà collegano il bene alla stessa uri di dd:MeasurementCollection, in cui sono presenti sia l'altezza -sotto dd:hasMeasurement, che le altre misure - sotto core:note). 
Ci sono eventualmente altri esempi in cui viene riprodotto questo problema?
