### ISSUE TITLE
a-cat:iccdNormTag / core:iccdNormTag

### ISSUE THREAD

**Issue by Valentina10** [ICCD-MiBACT/ArCo#162]
**Indicate which part of the project the bug concerns: ontology, knowledge graph, rdfizer**
ontology

**Describe the bug**
In some cases, core:iccdNormTag is erroneously used in place of a-cat:iccdNormTag

**To Reproduce**
SELECT DISTINCT ?ontEnt
WHERE {?ontEnt core:iccdNormTag ?o}

**Expected behavior**
?ontEnt a-cat:iccdNormTag ?o

**Comment by margherita-porena** [comment]
The issue has been solved with the commits in the previous comments
