### ISSUE TITLE
Filtrare valore MNR nelle schede per non pubblicarlo

### ISSUE THREAD

**Issue by ICCD-MiBACT** [ICCD-MiBACT/ArCo#163]
Nel caso le misure del bene culturale non siano rilevate (MNR) il dato non va recuperato da SIGEC.
Vedi ad esempio: https://w3id.org/arco/resource/HistoricOrArtisticProperty/0900305425-1

Il trattamento, cioè, deve essere il medesimo riservato ai valori NR, negli altri campi

**Comment by margherita-porena** [comment]
The issue has been closed with commit 7298464
