### ISSUE TITLE
Dati amministrativi

### ISSUE THREAD

**Issue by ICCD-MiBACT** [ICCD-MiBACT/ArCo#165]
I dati amministrativi vanno recuperati dinamicamente da qui:

http://catalogo.beniculturali.it/oaitarget/OAIHandler?verb=AdministrativeData

dove sono presenti 
Enti Base
Enti Completo Records
Assegnazione 
Campagne
Attività
Progetti

**Comment by margherita-porena** [comment]
The issue has been solved with commit 8ad7c44
