### ISSUE TITLE
Label contenitore fisico

### ISSUE THREAD

**Issue by ICCD-MiBACT** [ICCD-MiBACT/ArCo#166]
​Per migliorare la situazione attuale della mappa che mostra anche le opere mobili immobilizzata dentro dei contenitori fisici che hanno attualmente come label "contenitore fisico" derivante dalle regole di trasformazione, indicare come label del contenitore fisico, in assenza del campo LDCN il campo LDCT (a-loc:hasSiteType), e in assenza di LDCT indicare LDCU

**Comment by margherita-porena** [comment]
The issue has been closed with commit bb5d9c7
