### ISSUE TITLE
Miglioramento rdfs:lbel

### ISSUE THREAD

**Issue by ICCD-MiBACT** [ICCD-MiBACT/ArCo#168]
Si suggerisce di rivedere le modalità con cui si compone la rdfs:label.
In particolare per i beni mobili è opportuno aggiungere il contenitore fisico (separato dal resto da un trattino). Per i beni immobili si dovrebbe eliminare il riferimento all'autore (o all'ambito culturale) e andrebbe invece aggiunto il Comune.

**Comment by margherita-porena** [comment]
La modifica alle label dei beni immobili è stata fatta con i commit di cui sopra, tuttavia per le label dei beni mobili, se inserisco il riferimento ai contenitori fisici, si possono creare delle label un po' strane quando non è indicato nella scheda il nome del contenitore fisico.
Ad esempio questo bene https://w3id.org/arco/resource/ArchaeologicalProperty/0300026648 avrebbe come label: 
amuleto (epoca tarda) - Contenitore fisico di Museo di Palazzo Ducale
