### ISSUE TITLE
Modifiche al Link alla scheda PDF

### ISSUE THREAD

**Issue by ICCD-MiBACT** [ICCD-MiBACT/ArCo#169]
Il modo in cui viene generato il link alla scheda PDF per le schede proveniente da SIGEC è stato modificato.
Adesso il link si forma così: http://sigecweb.beniculturali.it/sigec/item/print/ICCD9976890
Dove ICCD9976890 è il keycode della scheda di Catalogo

**Comment by luigi-asprino** [comment]
non modificato rdfizer, basta invocare rdfizer con il parametro corretto.
Nell’ultima release abbiamo aggiunto la possibilità di modificare il prefisso dei PDF.
Maggiori indicazioni sono fornite [qui](https://github.com/ICCD-MiBACT/ArCo/tree/master/ArCo-release/rdfizer#transformer)
