### ISSUE TITLE
molteplicità BNB/RB/RBR/RBRA

### ISSUE THREAD

**Issue by oibaf** [ICCD-MiBACT/ArCo#170]
**Indicare quali parti del progetto sono coinvolte nel bug: ontologia, knowledge graph, rdfizer**

rdfizer

**Descrivere il problema**

in presenza di più istanze del dato BNB/RB/RBR/RBRA la trasformazione non va a buon fine generando un'eccezione

Type error at char 20 in xsl:variable/@select on line 3755 column 102 (BNB.xslt)
  XPTY0004: A sequence of more than one item is not allowed as the first argument of split()

**Descrivere come riprodurre il problema**

ICCD14363167, ICCD14361375, ICCD14361363, ICCD14361355...

**Comportamento atteso**

la trasformazione va a buon fine

**Comment by margherita-porena** [comment]
The issue has been closed with commit 0864bcb
