### ISSUE TITLE
trasformazione del dato BNB/SB/SBE/SBEL

### ISSUE THREAD

**Issue by oibaf** [ICCD-MiBACT/ArCo#171]
**Indicare quali parti del progetto sono coinvolte nel bug: ontologia, knowledge graph, rdfizer**

rdfizer

**Descrivere il problema**

la trasformazione del dato in BNB/SB/SBE/SBEL genera un'eccezione

[main] (ErrorHandlerFactory.java:84) - [line: xx, col: yy] {E205} rdf:Description is not allowed as an element tag here.
[main] (Converter.java:301)

**Descrivere come riprodurre il problema**

ICCD11783702, ICCD11783664, ICCD11783654, ICCD11783340...

**Comportamento atteso**

la trasformazione va a buon fine

**Comment by margherita-porena** [comment]
The issue has been solved with commit 751d761
