### ISSUE TITLE
la risorsa <https://w3id.org/arco/ontology/immovable-property/ConstructionDesign> non risulta collegata al bene (e non veicola informazione)

### ISSUE THREAD

**Issue by oibaf** [ICCD-MiBACT/ArCo#172]
**Indicare quali parti del progetto sono coinvolte nel bug: ontologia, knowledge graph, rdfizer**

rdfizer

**Descrivere il problema**

nel titolo

**Descrivere come riprodurre il problema**

ICCD11874650, ICCD11869117, ICCD11869079, ICCD11386606...

**Comportamento atteso**

presenza del collegamento al bene e del dato pertinente

**Comment by margherita-porena** [comment]
The issue has been solved with commit da7facf
