### ISSUE TITLE
la risorsa <https://w3id.org/arco/ontology/context-description/Bibliography> non risulta collegata al bene (tranne nel dato testuale)

### ISSUE THREAD

**Issue by oibaf** [ICCD-MiBACT/ArCo#173]
**Indicare quali parti del progetto sono coinvolte nel bug: ontologia, knowledge graph, rdfizer**

rdfizer

**Descrivere il problema**

nel titolo

**Descrivere come riprodurre il problema**

ICCD11875517

**Comportamento atteso**

collegamento della risorsa al bene pertienete

**Comment by margherita-porena** [comment]
The issue has been closed with commit 84d0160
