### ISSUE TITLE
la risorsa <https://w3id.org/arco/ontology/movable-property/Cleavage> non ha collegamento al bene (tranne nel dato testuale)

### ISSUE THREAD

**Issue by oibaf** [ICCD-MiBACT/ArCo#174]
**Indicare quali parti del progetto sono coinvolte nel bug: ontologia, knowledge graph, rdfizer**

rdfizer

**Descrivere il problema**

nel titolo

**Descrivere come riprodurre il problema**

ICCD12096508, ICCD12096544, ICCD12096510, ICCD12096548...

**Comportamento atteso**

collegamento della risorsa al bene pertinente

**Comment by margherita-porena** [comment]
The issue has been closed with commit bc19ec5
