### ISSUE TITLE
la risorsa <https://w3id.org/arco/ontology/context-description/ConservationIntervention> non ha collegamento al bene (tranne nel dato testuale)

### ISSUE THREAD

**Issue by oibaf** [ICCD-MiBACT/ArCo#175]
**Indicare quali parti del progetto sono coinvolte nel bug: ontologia, knowledge graph, rdfizer**

rdfizer

**Descrivere il problema**

nel titolo

**Descrivere come riprodurre il problema**

ICCD14178386

**Comportamento atteso**

collegamento della risorsa al bene pertinente

**Comment by margherita-porena** [comment]
The issue has been sovled with commit f20334a
