### ISSUE TITLE
la risorsa <https://w3id.org/arco/ontology/denotative-description/CulturalEntityTechnicalStatus> non è collegata al bene (tranne nel dato testuale)

### ISSUE THREAD

**Issue by oibaf** [ICCD-MiBACT/ArCo#176]
**Indicare quali parti del progetto sono coinvolte nel bug: ontologia, knowledge graph, rdfizer**

rdfizer

**Descrivere il problema**

nel titolo

**Descrivere come riprodurre il problema**

`<https://w3id.org/arco/resource/CulturalEntityTechnicalStatus/0900184928>` @ICCD9473289
`<https://w3id.org/arco/resource/CulturalEntityTechnicalStatus/0900185176>` @ICCD9473268
`<https://w3id.org/arco/resource/CulturalEntityTechnicalStatus/1100182123>` @ICCD2912434
`<https://w3id.org/arco/resource/CulturalEntityTechnicalStatus/1100182290>` @ICCD2912768
...

**Comportamento atteso**

collegamento della risorsa al bene pertinente

**Comment by margherita-porena** [comment]
The issue has been solved woth commit 8079b56
