### ISSUE TITLE
problemi con la datazione

### ISSUE THREAD

**Issue by smazzini** [ICCD-MiBACT/ArCo#18]
esempio: http://wit.istc.cnr.it/lodview/resource/TimeInterval/sec-xvi.html

Come viene gestita la datazione?
Questa utilizzata ora nei dati non sembra utile

**Comment by Valentina10** [comment]
Purtroppo nella produzione dei dati della seconda release c'è stato un errore per quanto riguarda la datazione. Per la prossima release procederemo così: l'Event collegato alla Dating del bene culturale avrà associati due timeinterval, uno, obbligatoriamente presente, per la cronologia generica (il secolo, con eventuale specifica sulla validità delle datazione, es "circa") e uno per l'eventuale cronologia specifica (anno di inizio e anno di fine, con eventuale specifica sulla validità); il primo sarà collegato con tiapit:atTime e il secondo con una proprietà specifica "specificTime".
