### ISSUE TITLE
collegamento al bene / implementazione di risorse <https://w3id.org/arco/ontology/denotative-description/MeasurementCollection>

### ISSUE THREAD

**Issue by oibaf** [ICCD-MiBACT/ArCo#180]
**Indicare quali parti del progetto sono coinvolte nel bug: ontologia, knowledge graph, rdfizer**

rdfizer

**Descrivere il problema**

nel titolo

**Descrivere come riprodurre il problema**

nei casi riportati di seguito le risorse indicate risultano non implementate o non collegate

`<https://w3id.org/arco/resource/MeasurementCollection/2000243404-vertical-element-measurement-collection2>` @ICCD13565898
`<https://w3id.org/arco/resource/MeasurementCollection/2000243404-vertical-element-measurement-collection1>` @ICCD13565898
`<https://w3id.org/arco/resource/MeasurementCollection/1201339462-vertical-element-measurement-collection2>` @ICCD13705060
`<https://w3id.org/arco/resource/MeasurementCollection/1201339462-vertical-element-measurement-collection1>` @ICCD13705060
`<https://w3id.org/arco/resource/MeasurementCollection/1500865969-vertical-element-measurement-collection4>` @ICCD13698638
`<https://w3id.org/arco/resource/MeasurementCollection/1500865969-vertical-element-measurement-collection2>` @ICCD13698638
`<https://w3id.org/arco/resource/MeasurementCollection/1400068105-vertical-element-measurement-collection1>` @ICCD12004850
`<https://w3id.org/arco/resource/MeasurementCollection/1400068105-vertical-element-measurement-collection5>` @ICCD12004850
`<https://w3id.org/arco/resource/MeasurementCollection/1400068104-vertical-element-measurement-collection3>` @ICCD12004842
`<https://w3id.org/arco/resource/MeasurementCollection/1400068104-vertical-element-measurement-collection2>` @ICCD12004842

**Comportamento atteso**

il collegamento / l'implementazione della risorsa

**Comment by margherita-porena** [comment]
The issue has been solved wih commit 4d4ae2e
