### ISSUE TITLE
collegamento al bene / implementazione di risorse <https://w3id.org/arco/ontology/context-description/PrintingPlatesSeries>

### ISSUE THREAD

**Issue by oibaf** [ICCD-MiBACT/ArCo#181]
**Indicare quali parti del progetto sono coinvolte nel bug: ontologia, knowledge graph, rdfizer**

rdfizer

**Descrivere il problema**

nel titolo

**Descrivere come riprodurre il problema**

nei casi riportati di seguito le risorse indicate risultano non implementate o non collegate

`<https://w3id.org/arco/resource/PrintingPlatesSeries/0500260572-0->` @ICCD8404633
`<https://w3id.org/arco/resource/PrintingPlatesSeries/0500260572-0-mythologia-pagana>` @ICCD8404633
`<https://w3id.org/arco/resource/PrintingPlatesSeries/0500260562-2-icnografia-generale-del-palazzo-di-caprarola-dellillustriss-cardinal-farnese>` @ICCD8404609
`<https://w3id.org/arco/resource/PrintingPlatesSeries/0500260562-2->` @ICCD8404609
`<https://w3id.org/arco/resource/PrintingPlatesSeries/0500212575-7-amori-sdegni-e-gelosie-di-giunone>` @ICCD8404008
`<https://w3id.org/arco/resource/PrintingPlatesSeries/0500212575-7->` @ICCD8404008
`<https://w3id.org/arco/resource/PrintingPlatesSeries/0500677713->` @ICCD11145155
`<https://w3id.org/arco/resource/PrintingPlatesSeries/0500677713-%E8%BF%91%E6%B1%9F%E5%85%AB%E6%99%AF%E4%B9%8B%E5%86%85-omi-hakkei-no-uchi-gli-otto-panorami-di-omi>` @ICCD11145155
...

**Comportamento atteso**

il collegamento / l'implementazione della risorsa

**Comment by margherita-porena** [comment]
The issue has been solved with commit 183da2f
