### ISSUE TITLE
Proper Title

### ISSUE THREAD

**Issue by smazzini** [ICCD-MiBACT/ArCo#19]
lanciando sull'endpoint questa query 
select distinct * where {?c <https://w3id.org/arco/cpdescription/properTitle> ?properTitle} LIMIT 100
si può notare che il campo del title proper è stato valorizzato con il Luogo.

**Comment by Valentina10** [comment]
Su properTitle viene mappato il campo SG/SGT/SGTP. 
Ecco un esempio da una scheda xml che ha nel campo SGTP il nome di una città, relativamente alla risorsa (manifesto) http://wit.istc.cnr.it/lodview/resource/HistoricOrArtisticProperty/0500659575.html:
<SGT hint="SOGGETTO">
            <SGTI hint="Identificazione">torri e portici di Bologna</SGTI>
            <SGTP hint="Titolo proprio">Bologna</SGTP>
</SGT>

Qui invece, per esempio, properTitle è compilato in maniera diversa http://wit.istc.cnr.it/lodview/resource/HistoricOrArtisticProperty/0500260695-5.html

Immagino quindi dipenda dalle tipologie di beni

**Comment by smazzini** [comment]
A questo punto abbiamo due domande: 
1. nella normativa non troviamo riferimento al campo SGTP, a noi risulta che il titolo si trovi in SGTT.
2. nell'ontologia il proper title è definito così "This property represents the proper title of a cultural property" e non ci sembra che, anche nell'esempio che riporti, "Bologna"sia il titolo proprio di quell'opera. Quindi forse questo tema merita una riflessione più approfondita

**Comment by Valentina10** [comment]
SGTP si trova nella normativa S (dalla normativa: "Per titolo proprio di una stampa si intende il titolo principale nella forma in cui appare sulla stampa stessa."); il campo SGTT è invece mappato sulla datatype più generica "title" 
select distinct * where {?c <https://w3id.org/arco/cpdescription/title> ?Title} 
ma nella prossima release sarà rappresentato anche con object property. 

Preciso che HistoricOrArtisticProperty è una classe che si riferisce ai Beni storici e artistici, ovvero fa riferimento alle normative: OA, OAC, D, MI, S, VeAC. Provvederemo a integrare i comment di classi e proprietà dell'ontologia, per rendere la semantica e la mappatura più chiare! Inoltre useremo una annotation property per indicare il path esatto nella normativa che corrisponde a una certa proprietà o classe, a questo punto anche specificando la normativa, per questi casi particolari.
