### ISSUE TITLE
CF/CF/CFD

### ISSUE THREAD

**Issue by oibaf** [ICCD-MiBACT/ArCo#190]
**Indicare quale componente del progetto si riferisce la richiesta**

rdfizer

**La richiesta è relativo ad un problema?**

nella trasformazione dei contenitori fisici il contenuto della descrizione non viene restituito

**Descrivi la soluzione che ti piacerebbe avere**

la presenza del dato in CF/CF/CFD anche nel formato RDF

**Comment by margherita-porena** [comment]
The issue has been solved with commit cc6b3f5
