### ISSUE TITLE
trasformazione contenitori (CF-CG.xslt)

### ISSUE THREAD

**Issue by oibaf** [ICCD-MiBACT/ArCo#191]
**Indicare quali parti del progetto sono coinvolte nel bug: ontologia, knowledge graph, rdfizer**

rdfizer

**Descrivere il problema**

collegamento dei dati di georeferenziazione e di redazione

alle righe 262 e 1822 (rev,1742) di CF-CG.xslt la composizione dell'identificativo della risorsa è incompleto

`concat($NS, '/',` => `concat($NS, 'CatalogueRecordVersion/',`

alla riga 770 il test sulla presenza del dato in GE non dà mai esito positivo

`test="record/metadata/schede/*/GE/*/*"` => `test="*/*"`

**Descrivere come riprodurre il problema**

ad esempio ICCD13329725, ICCD12380209...

**Comment by margherita-porena** [comment]
The issue has been closed with commit 4d79f28
