### ISSUE TITLE
riferemento al contenitore (arco.xslt)

### ISSUE THREAD

**Issue by oibaf** [ICCD-MiBACT/ArCo#192]
**Indicare quali parti del progetto sono coinvolte nel bug: ontologia, knowledge graph, rdfizer**

rdfizer

**Descrivere il problema**

l'identificativo della risorsa nel riferimento al contenitore non è corretto (riga 26555 di arco.xslt rev.1742)

`<xsl:value-of select="concat($NS, 'Site/', $idCF)" />`

 =>
```
<xsl:value-of select="'http://dati.beniculturali.it/iccd/cf/resource/CulturalInstituteOrSite/'" />
<xsl:choose>
 <xsl:when test="contains($idCF, 'DBunico')"><xsl:value-of select="substring-after($idCF, 'DBunico')"/></xsl:when>
 <xsl:otherwise><xsl:value-of select="$idCF"/></xsl:otherwise>
</xsl:choose>

```

**Descrivere come riprodurre il problema**

ad esempio ICCD8548954

**Comportamento atteso**

la risorsa viene referenziata correttamente

**Comment by margherita-porena** [comment]
The issue has been solved with commit 4536c2f
