### ISSUE TITLE
collegamento a risorse <https://w3id.org/italia/onto/CLV/Geometry> nei CF

### ISSUE THREAD

**Issue by oibaf** [ICCD-MiBACT/ArCo#194]
**Indicare quali parti del progetto sono coinvolte nel bug: ontologia, knowledge graph, rdfizer**

rdfizer

**Descrivere il problema**

clvapit:hasGeometry  è presente anche quando l'elemento CF/GE è vuoto (e la risorsaa non è implementata in rdf)

**Descrivere come riprodurre il problema**

ad esempio ICCD12360714, ICCD12360719, ICCD12360853, ICCD12360868, ICCD12360874...

**Comportamento atteso**

il riferimento alla risorsa in presenza del dato

**Comment by margherita-porena** [comment]
The issue has been solved with commit d666723
