### ISSUE TITLE
riferimenti a immagini nei CF

### ISSUE THREAD

**Issue by oibaf** [ICCD-MiBACT/ArCo#195]
**Indicare quale componente del progetto si riferisce la richiesta**

rdfizer

**La richiesta è relativo ad un problema?**

la presenza di immagini non è evidenziata nella scheda del contenitore fisico

**Descrivi la soluzione che ti piacerebbe avere**

il dato in CF/DO/FTA/FTAN genera il riferimento all'immagine anche sulla risorsa <https://dati.beniculturali.it/lodview/cis/Site>

**Comment by margherita-porena** [comment]
Dal testing della scheda http://www.catalogo-old.beniculturali.it/oaitarget/OAIHandler?verb=GetRecord&metadataPrefix=oai_dc&identifier=oai:oaicat.iccd.org:@ICCD13329725@/xml/contenitori_fisici le immagini risultano associate alla risorsa tramite la proprietà foaf:depiction
