### ISSUE TITLE
completezza dei dati in elementi ripetibili (maxOccurs > 1)

### ISSUE THREAD

**Issue by oibaf** [ICCD-MiBACT/ArCo#196]
**Indicare quali parti del progetto sono coinvolte nel bug: ontologia, knowledge graph, rdfizer**

rdfizer

**Descrivere il problema**

per alcuni dei dati presenti alla fonte in elementi ripetibili, l'elaborazione si limita alla prima istanza

**Descrivere come riprodurre il problema**

UTU ICCD14096057, ICCD14298501
USO ICCD14295730
DESN ICCD4689511
MISV ICCD11937406
ATB ICCD14291641
DTF ICCD8531832
OGA ICCD9143247
OGD ICCD13124957
OGTP ICCD10088602
OGCD ICCD14371179
STC CCD12095643
SGTI SGTT ICCD13074440 ICCD11324919
SPS,LRV) ICCD12087343 ICCD12085339
...

**Comportamento atteso**

la rappresentazione completa dei dati

**Informazioni aggiuntive**

una proposta di soluzione è presente nella [patch](https://github.com/ICCD-MiBACT/ArCo/files/5975805/ArCo-release-1.2.patch.zip) allegata, che comporta una migrazione alla versione 2.0 di XSLT

tra i vantaggi offerti da 2.0, il richiamo al problema è ben rappresentato da questa nota del [documento di specifiche](https://www.w3.org/TR/xpath20/#id-incompat-in-false-mode):

>When a node-set containing more than one node is supplied as an argument to a function or operator that expects a single node or value, the XPath 1.0 rule was that all nodes after the first were discarded. Under XPath 2.0, a type error occurs if there is more than one node.

la presenza di richiami a funzioni nel trattamento del dato (normalize-space è il caso diffuso) comporta quindi la segnalazione esplicita delle anomalie evidenziate

nella patch non sono approfonditi i casi in cui la presenza di ripetizioni richiede un opportuno trattamento del contesto

le verifiche sono state estese al campione completo dei dati pubblicati attualmente dal servizio OAI

la patch allegata implementa anche una possibile soluzione alle segnalazioni #198 e #197

**Comment by luigi-asprino** [comment]
Grazie per la segnalazione.
Potresti aprire una fork del progetto e poi fare una pull request del delle modifiche, questo ci da modo di verificare le modifiche in maniera controllata e usare eventualmente il versionamento se qualcosa dovesse andare storto.

**Comment by oibaf** [comment]
eccola #206

**Comment by margherita-porena** [comment]
The issue has been solved with commit 0ceaeb4
