### ISSUE TITLE
riferimenti alle risorse nelle EMM collegate a FTAN sui contenitori

### ISSUE THREAD

**Issue by oibaf** [ICCD-MiBACT/ArCo#197]
**Indicare quale componente del progetto si riferisce la richiesta**

rdfizer

**La richiesta è relativo ad un problema?**

i riferimenti alle risorse nelle EMM collegate a FTAN sono presenti nelle PhotographicDocumentation ma non sui contenitori

**Descrivi la soluzione che ti piacerebbe avere**

i riferimenti alle risorse nelle EMM collegate a FTAN anche sui contenitori (analogamente a quanto già implementato per le schede di catalogo)

**Informazioni aggiuntive**

una possibile soluzione è implementata nella patch allegata alla segnalazione #196

**Comment by margherita-porena** [comment]
The issue has been closed with commit 3a4d8
