### ISSUE TITLE
geocoding contenitori

### ISSUE THREAD

**Issue by oibaf** [ICCD-MiBACT/ArCo#198]
**Indicare quale componente del progetto si riferisce la richiesta**

rdfizer

**La richiesta è relativo ad un problema?**

i dati di geocoding nella scheda oai (harvesting/geocoding) non sono riportati nella rappresentazione RDF

**Descrivi la soluzione che ti piacerebbe avere**

i dati di geocoding nella rappresentazione RDF (i dati di georeferenziazione in GE non sono sempre presenti)

**Informazioni aggiuntive**

una possibile soluzione è implementata nella patch allegata alla segnalazione #196

**Comment by margherita-porena** [comment]
The issue has been solved with commit 0ceaeb4
