### ISSUE TITLE
hasUseFunction nei contenitori fisici

### ISSUE THREAD

**Issue by oibaf** [ICCD-MiBACT/ArCo#199]
**Indicare quali parti del progetto sono coinvolte nel bug: ontologia, knowledge graph, rdfizer**

rdfizer

**Descrivere il problema**

l'IRI oggetto della proprietà <https://w3id.org/arco/ontology/context-description/hasUseFunction> è incompleta

**Descrivere come riprodurre il problema**

tutti i CF che implementano la proprietà, ad esempio ICCD14546098

**Comportamento atteso**

la composizione corretta dell'IRI

**Informazioni aggiuntive**

probabilmente un refuso nel dato letto nel comporre l'IRI in CF-CG.xslt LC/LDC/LDCF => CF/CFU

**Comment by margherita-porena** [comment]
The issue has been closed with commit e627b87
