### ISSUE TITLE
Metadato di categoria  dai dati in CIDOC-CRM (endpoint di Culturaitalia)

### ISSUE THREAD

**Issue by simonegasperoni** [ICCD-MiBACT/ArCo#2]
Sullo SPARQL endpoint di culturaitalia http://dati.culturaitalia.it/sparql/index.jsp?locale=it ci sono delle risorse descritte con il CIDOC-CRM, trovo sia facile realizzare un ponte tra le risorse ArCo (schede ICCD)  e quelle CIDOC-CRM tramite il codice identificativo delle schede di catalogo ICCD, così facendo si potrebbe - ad esempio - riutilizzare il metadato di categoria del tesauro PICO quando il bene è presente nella bancadati di culturaitalia.

**Comment by luigi-asprino** [comment]
@simonegasperoni grazie per la segnalazione.
Se ho capito bene suggeriva di fare un entity linking.
Può farmi un esempio.
Mi servirebbe quindi una query SPARQL su ArCo e una su http://dati.culturaitalia.it/sparql
Le query devono evidenziare le risorse collegabili.

**Comment by luigi-asprino** [comment]
Senza ulteriori informazioni per me è difficile capire come implementare il linking.
Quindi, per ora chiudo la issue.
Se ci saranno nuove indicazioni la riapriremo.

**Comment by ICCD-MiBACT** [comment]
[thesPICO.pdf](https://github.com/ICCD-MiBACT/ArCo/files/4610668/thesPICO.pdf)
Credo che questo file possa essere utile per l'allineamento

**Comment by luigi-asprino** [comment]
grazie per il tesauro, ma non era questo che mi bloccava. 
continua a sfuggermi quali sono le risorse di cultura italia che si vogliono allineare e come (o non ho proprio capito cosa viene suggerito nel messaggio).
viene suggerito nel primo messaggio di usare un id iccd che è presente in cultura italia, se mi indicate come:
1. come recuperare questo id dalle risorse di cultura italia
2. dove recuperare lo stesso id nelle schede xml 
posso occuparmi di realizzare il linking

**Comment by ICCD-MiBACT** [comment]
Su http://dati.culturaitalia.it/sparql dovrebbero essere indicizzati nostri beni, ma non so fare le query e i link agli skos sembrano non funzionare.

**Comment by simonegasperoni** [comment]
ciao luigi,
scusa non avevo visto i tuoi post
io vedo i codici delle schede ICCD su http://dati.culturaitalia.it/sparql 
guarda qui:
http://dati.culturaitalia.it/resource/thing/scheda-iccd-oa-10-00077819-a
due anni fa :) a quel workshop al mibact mi chiedevo perché non linkare da arco usando questi codici ICCD.. su ARCO dovreste avere questi codici ICCD

mi sembra che era questo il punto.. ma è passato molto tempo forse c'era altro

**Comment by simonegasperoni** [comment]
select * where { ?A ?S <http://dati.culturaitalia.it/resource/thing/scheda-iccd-oa-10-00077819-a>} LIMIT 1000

**Comment by luigi-asprino** [comment]
Peccato che l'id della scheda viene inserito solo nella URI e non c'è una proprietà che lo specifica.
Non penso che riuscirò a fare linking con gli strumenti standard, ma probabilmente questo richiederà fare uno script ad-hoc per questo.

**Comment by simonegasperoni** [comment]
c'è la rdfs:label scheda iccd OA: 10-00077819-A
non so se può considerasi al fine del linking, dipende se è valorizzata in modo uniforme in tutto il dataset

**Comment by luigi-asprino** [comment]
si il problema è uguale perché comunque bisogna far il parsing della label per estrarre i codici.

**Comment by luigi-asprino** [comment]
Ho creato un [moduletto](https://github.com/ICCD-MiBACT/ArCo/tree/master/ArCo-release/arco.linking#linking-culturaitalia) per fare il linking.
Questo fa il linking sia a livello di scheda che a livello di bene culturale.
[Qui](http://etna.istc.cnr.it/arco-data/linking/culturaItalia.nt) trovate un esempio di output.
Grazie e chiudo la issue.
