### ISSUE TITLE
Ente competente attuale

### ISSUE THREAD

**Issue by ICCD-MiBACT** [ICCD-MiBACT/ArCo#201]
E' stato aggiunto nel tag <harvesting> un ulteriore campo <enteCompetente>
http://catalogo.beniculturali.it/oaitarget/OAIHandler?verb=GetRecord&metadataPrefix=oai_dc&identifier=oai:oaicat.iccd.org:@ICCD11654870@/xml/cards). Questo valore andrà a SOSTITUIRE il valore presente in <ECP> nella scheda. Quindi bisogna aggiornare RDFizer.

La sostituzione riguarda solo le schede i cui è presente <entecompetente> in harvesting (si tratta di schede che hanno "migrato di competenza" e tale operazione viene gestita nel SIGEC senza che ciò si traduca in una modifica dei dati nella scheda che noi vediamo nell'xml della scheda). Quindi se c'è <entecompetente> in harvesting​ l'ECP viene sostituito, altrimenti vive l'ECP.

La sigla presente nei dati va sciolta usando la tabella Enti completo

**Comment by margherita-porena** [comment]
The issue has been solved with commit 8ad7c44
