### ISSUE TITLE
Inversione ordine delle immagini in pico:preview e in foaf:depiction

### ISSUE THREAD

**Issue by ICCD-MiBACT** [ICCD-MiBACT/ArCo#202]
L'ordine delle immagini presente in SIGEC ed esposto in harvesting va rispettato.
Al momento sembra che **l'ordine sia rispettato in a-cd:hasDocumentation ma non in pico:preview e in foaf:depiction**

Vedi ad esempio: https://dati.beniculturali.it/esource/ArchaeologicalProperty/0500699764.html

**Comment by margherita-porena** [comment]
L'ordine di di presentazione delle immagini è deciso dallo sparql endpoint che restituisce i dati
