### ISSUE TITLE
Uniformare trattamento schede BDM

### ISSUE THREAD

**Issue by ICCD-MiBACT** [ICCD-MiBACT/ArCo#203]
vedi ad esempio:
https://dati.beniculturali.it/lodview-arco/resource/DemoEthnoAnthropologicalHeritage/0900560288.html

https://dati.beniculturali.it/lodview-arco/resource/DemoEthnoAnthropologicalHeritage/1201254202-3.html​

In alcuni casi manca la lingua alla label, in alcuni casi, come quello che ha il gilé come bene componente, mancano praticamente tutte le proprietà di arco, ci sono solo quelle pico e dcmi

**Comment by margherita-porena** [comment]
Il link della seconda risorsa non è più navigabile. Tuttavia ho testato la scheda (http://www.catalogo-old.beniculturali.it/oaitarget/OAIHandler?verb=GetRecord&metadataPrefix=oai_dc&identifier=oai:oaicat.iccd.org:@ICCD13668668@/xml) e vengono create le triple relative alle proprietà di arco e alle label in italiano e in inglese.
Potreste inviarmi il link ad un'altra risorsa che riproduce lo stesso problema?

**Comment by ICCD-MiBACT** [comment]
Il link era errato: https://dati.beniculturali.it/lodview-arco/resource/DemoEthnoAnthropologicalHeritage/1201254202-3.html

(scriveva due volte html alla fine)

**Comment by margherita-porena** [comment]
The issue has been solved with commit 1912d2d
