### ISSUE TITLE
Sciogliere sigla ESC

### ISSUE THREAD

**Issue by ICCD-MiBACT** [ICCD-MiBACT/ArCo#204]
Anche ESC va sciolta secondo la tabella degli Enti.
Vedi ad esempio qui: https://www.catalogo.beniculturali.it/detail/ScientificOrTechnologicalHeritage/0900918452

**Comment by margherita-porena** [comment]
The issue has been solved with commit 50e0c93 and 4ec20ae

**Comment by ICCD-MiBACT** [comment]
Nella Label va distinta la sigla dallo scioglimento, perchè altrimenti non è usabile nel sito:
vedi https://dati.beniculturali.it/lodview-arco/resource/Agent/046d26cbb34ae11c0d684aaf85ede636.html

**Comment by ICCD-MiBACT** [comment]
Carissimi questa issue è rimasta ancora irrisolta e crea problemi sul sito. Vi prego di prenderla in carico, come avevamo detto, usando skos:prefLabel per la denominazione sciolta

**Comment by margherita-porena** [comment]
The issue has been solved with commit 1912d2d
