### ISSUE TITLE
typos in URIs

### ISSUE THREAD

**Issue by Valentina10** [ICCD-MiBACT/ArCo#205]
# English Version

**Indicate which part of the project the bug concerns: ontology, knowledge graph, rdfizer**
ontology

**Describe the bug**
typos in URIs

**To Reproduce**
movable-property module
https://w3id.org/arco/ontology/movable-property/alfaParameter
https://w3id.org/arco/ontology/movable-property/CalcualtedDensity

**Expected behavior**
https://w3id.org/arco/ontology/movable-property/AlfaParameter (or https://w3id.org/arco/ontology/movable-property/AlphaParameter ?)
https://w3id.org/arco/ontology/movable-property/CalculatedDensity

**Additional context**

**Comment by margherita-porena** [comment]
The issue has been solved with commit e5991f1

**Comment by Valentina10** [comment]
other typo: https://w3id.org/arco/ontology/movable-property/isCloseIndivisualOf

**Comment by margherita-porena** [comment]
The issue has been solved with commit 13316d4
