### ISSUE TITLE
Transitività della relazione a-cd:hasUrbanPlanningEnvironmentalRelationWith

### ISSUE THREAD

**Issue by ICCD-MiBACT** [ICCD-MiBACT/ArCo#209]
La relazione che è espressa a partire da un bene (ad esempio https://w3id.org/arco/resource/ArchitecturalOrLandscapeHeritage/0800243363) non viene visualizzata nell'altro bene (https://w3id.org/arco/resource/ArchitecturalOrLandscapeHeritage/0800243362)

**Comment by margherita-porena** [comment]
The relation is symmetric, but there were a problem in the uri.
The issue has been solved with commit fd0d964
