### ISSUE TITLE
typos in URIs and labels

### ISSUE THREAD

**Issue by Valentina10** [ICCD-MiBACT/ArCo#210]
**Indicate which part of the project the bug concerns: ontology, knowledge graph, rdfizer**
ontology

**Describe the bug**
typos in URIs

**To Reproduce**
https://w3id.org/arco/ontology/context-description/isPartecipantOf (uri)
https://w3id.org/arco/ontology/context-description/hasPartecipant (uri)
https://w3id.org/arco/ontology/context-description/hasFinalist rdfs:label has patercipant / ha partecipante (label)

**Expected behavior**
https://w3id.org/arco/ontology/context-description/isParticipantOf
https://w3id.org/arco/ontology/context-description/hasParticipant
https://w3id.org/arco/ontology/context-description/hasFinalist rdfs:label has finalist / ha finalista

**Comment by margherita-porena** [comment]
The issue has been closed with commit 3a4d8
