### ISSUE TITLE
Manca nell'ontologia la  classe CatalogueRecordMODI

### ISSUE THREAD

**Issue by ICCD-MiBACT** [ICCD-MiBACT/ArCo#217]
Nell'ontologia non sembra dichiarata la nuova classe CatalogueRecordMODI
https://github.com/ICCD-MiBACT/ArCo/blob/master/ArCo-release/ontologie/catalogue/catalogue.owl
che deve essere dichiarata come sottoclasse di CatalogueRecord. 
L'ontologia aggiornata deve essere caricata in endpoint

**Comment by margherita-porena** [comment]
La classe è stata creata nellìontologia, ma si strova nella versione 1.2.
Questa è l'URI: 
https://w3id.org/arco/ontology/catalogue/CatalogueRecordMODI
