### ISSUE TITLE
rdfs:label su risorse <https://w3id.org/arco/ontology/arco/CulturalPropertyPart>

### ISSUE THREAD

**Issue by oibaf** [ICCD-MiBACT/ArCo#219]
**Indicare quali parti del progetto sono coinvolte nel bug: ontologia, knowledge graph, rdfizer**

rdfizer

**Descrivere il problema**

su alcune delle risorse `<https://w3id.org/arco/ontology/arco/CulturalPropertyPart>` la property rdfs:label é assente

**Descrivere come riprodurre il problema**

https://dati.beniculturali.it/sparql?query=select+distinct%3Fs%7Bgraph%3Chttps%3A%2F%2Fw3id.org%2Farco%2Fdata%3E%7B%3Fs+a%3Chttps%3A%2F%2Fw3id.org%2Farco%2Fontology%2Farco%2FCulturalPropertyPart%3Eminus%7B%3Fs+rdfs%3Alabel%3Fl%7D%7D%7D%231544

**Comportamento atteso**

l'implementazione della property

**Comment by margherita-porena** [comment]
The issue has been closed with commit 3a4d8
