### ISSUE TITLE
ontologie riutilizzate

### ISSUE THREAD

**Issue by smazzini** [ICCD-MiBACT/ArCo#22]
non ci risulta chiaro il motivo del riutilizzo delle ontologie che risiedono in questa base 
https://w3id.org/italia/onto/
non sono dereferenziate, non sono stabili e spesso ci sembrano la copia di ontologie più note e diffuse (es: foaf, pro)

**Comment by giorgialodi** [comment]
Ciao Silvia, 
siccome sto seguendo i lavori sullo sviluppo delle ontologie che citi e che sono disponibili su github Italia e integrate nella Piattaforma Digitale Nazionale dei Dati (articolo 50-ter del CAD, anche detto in inglese DAF - Data & Analytics Framework) posso darti informazioni maggiori:

1) le ontologie sono deferenziate. Esempio: https://ontopia.daf.teamdigitale.it/lodview/onto/ACCO.html Quello che manca, e che predisponiamo in questi giorni, è la definizione delle regole di redirect html di w3id.org/italia/ verso il dominio indicato.  Su questo mi sento quindi di dare rassicurazioni :) Anche i vocabolari controllati sono dereferenziati e interrogabili su SPARQL endpoint. 

2) E' vero che alcune ontologie non sono stabili. Ma l'indicazione della loro instabilità è chiaramente dichiarata nel relativo repository github (https://github.com/italia/daf-ontologie-vocabolari-controllati). Penso, ma qui chi segue il progetto ArCo può rispondere meglio di me, ci sia comunque una volontà di seguire una strategia nazionale coordinata, su elementi che sono indipendenti dallo specifico dominio (e.g., modelli per le persone, per le organizzazioni, per i luoghi/indirizzi). L'idea penso sia proprio di collegarsi direttamente a ontologie di riferimento nazionale (citate nelle linee guida nazionali), vincolandosi anche ai possibili cambiamenti che in quelle ontologie si verificano. Personalmente trovo la cosa positiva, anche se ancora in uno scenario che potrebbe subire dei cambiamenti (ma non stravolgimenti). 

3) Le ontologie presenti sul repository di github italia sono realizzate seguendo una precisa strategia di modellazione che ben si sposa  con i requisiti derivanti da diversi contesti collaterali in cui vengono utilizzate (come nel caso del DAF, ma non solo) dove una semantica self-cointained è preferibile. La strategia è quella del riuso indiretto di ontologie esterne al contesto nazionale italiano già presenti allo stato dell'arte (la strategia è anche documentata in pubblicazioni scientifiche delle persone che seguono, insieme al MIBACT, il progetto ArCo). Non c'entra nulla copiare concetti da altre ontologie, semmai si riusano, appunto, moduli, design pattern. Aggiungo che ci sono degli elementi nelle ontologie w3id.org/italia/onto che sono specifici del contesto italiano (ci sono svariati esempi nel caso dei luoghi e nel caso delle persone per esempio) per cui il riuso di solo ontologie come FOAF non è sufficiente. 
Se noti, nel repository indicato sopra, per ciascuna ontologia, ci sono anche i rispettivi allineamenti esterni che determinano i collegamenti delle ontologie w3id.org/italia/onto (della rete OntoPiA) a quelle esistenti nel Web dei Dati (alcune che citi) e soprattutto ai cosiddetti core vocabulary della Commissione Europa, che determinano il livello di interoperabilità semantica che possiamo realizzare come stato membro verso analoghe iniziative europee. Tra l'altro c'è un [issue aperto su github italia](https://github.com/italia/daf-ontologie-vocabolari-controllati/issues/2): se qualcuno vuole aiutarci ad arricchire gli allineamenti, è il benvenuto, in pieno spirito di comunità aperta :)

Spero questo possa fare più chiarezza su alcune caratteristiche delle ontologie sotto github italia e ti ringrazio per avermi dato la possibilità di chiarire questi punti. Ovviamente lascio ai responsabili del progetto ogni altra motivazione del perché le hanno adottate.

Ciao
Giorgia
