### ISSUE TITLE
URI ai link su Youtube (MODI) che sono in formato test e non URL

### ISSUE THREAD

**Issue by ICCD-MiBACT** [ICCD-MiBACT/ArCo#220]
Nei MODI sono presenti link a video su Youtube che non risultano URL nei LOD:

vedi ad esempio qui:

https://dati.beniculturali.it/sparql?default-graph-uri=&query=select+distinct+%3FURI+%3FyouTube+where+%7B%0D%0A%3FURI+a+%3Chttps%3A%2F%2Fw3id.org%2Farco%2Fontology%2Farco%2FDemoEthnoAnthropologicalHeritage%3E%3B+%3Chttps%3A%2F%2Fw3id.org%2Farco%2Fontology%2Fcontext-description%2FhasDocumentation%3E+%3FdocVideo.%0D%0Afilter+regex%28str%28%3FdocVideo%29%2C%27film%27%2C%27i%27%29%0D%0A%3FdocVideo+%3Chttps%3A%2F%2Fw3id.org%2Fitalia%2Fonto%2FSM%2FURL%3E+%3FyouTube%0D%0A%7D+limit+10&format=text%2Fhtml&timeout=0&debug=on

**Comment by margherita-porena** [comment]
The issue has been closed with commit 3a4d8
