### ISSUE TITLE
Relazioni schede madre schede figlie assenti

### ISSUE THREAD

**Issue by ICCD-MiBACT** [ICCD-MiBACT/ArCo#221]
La relazione tra schede madre e schede figlie ancora non funziona in alcuni casi.
vedi ad esempio 
questa https://dati.beniculturali.it/lodview-arco/resource/ArchaeologicalProperty/1201339483-1
è la figlia di https://dati.beniculturali.it/lodview-arco/resource/ArchaeologicalProperty/ArchaeologicalProperty/1201339483-0

**Comment by margherita-porena** [comment]
The issue has been closed with commit bf00251
