### ISSUE TITLE
Problema URI risorse (normalizzazione forzata dei valori di RVEL?)

### ISSUE THREAD

**Issue by ICCD-MiBACT** [ICCD-MiBACT/ArCo#222]
Se analizzate i risultati di [questa interrogazione](https://dati.beniculturali.it/sparql?query=select%3Fs+group_concat%28distinct%3Fx%2C%27+%27%29as%3Fx+group_concat%28distinct%3Fid%2C%27%3B+%27%29as%3Fid+group_concat%28distinct%3Fd%2C%27%3B+%27%29as%3Fd%7Bgraph%3Chttps%3A%2F%2Fw3id.org%2Farco%2Fdata%3E%7B%3Fs+a-cat%3AisDescribedByCatalogueRecord%2Fa-cat%3AsystemRecordCode%3Fx%3Ba-cat%3AisDescribedByCatalogueRecord%2Fa-cat%3AsystemRecordCode%3Fy%3Ba-cat%3AisDescribedByCatalogueRecord%2Fa-cat%3AlastUpdateDate%3Fd%3Bdc%3Aidentifier%3Fid+filter%28%3Fx%21%3D%3Fy%29%7D%7Dorder+by%3Fs) (fatta da Fabio) si notano molti casi di appiattimento del dato in RVEL con cui vengono costruiti gli URI dei beni dopo una elaborazione che comporta l'eliminazione del punto (nella tabella la colonna id riporta il dato composto con il valore originale che sopravvive nel dc:identifier)

In questi casi la duplicazione sembra dar luogo ad una impropria sovrapposizione di beni distinti, infatti entrambi i keycode trovano riscontro su OAI e restituiscono dati separati che vengono però confusi nella rappresentazione rdf

**Comment by margherita-porena** [comment]
The issue has been solved with commit dab65b3
