### ISSUE TITLE
Mappatura tutti i campi della scheda PG (iniziare da campo RAM)

### ISSUE THREAD

**Issue by ICCD-MiBACT** [ICCD-MiBACT/ArCo#228]
Dovremmo recuperare il campo RAM e il campo RENN dalla scheda PG  e verificare che la mappatura dei campi sia completa, eventualmente avvalendoci della collaborazione di Roma Tre

https://sigecweb.beniculturali.it/sigec/item/print/ICCD13877461

**Comment by margherita-porena** [comment]
The issue has been solved
