### ISSUE TITLE
allineamento enti schedatori ICCD

### ISSUE THREAD

**Issue by giorgiobevilacqua** [ICCD-MiBACT/ArCo#24]
Per chi cerca cose nel repository, sarebbe utile che gli enti schedatori (<https://w3id.org/arco/core/hasCataloguingAgency>) fossero allineati con l'elenco dell'ICCD:

http://www.catalogo.beniculturali.it/opendata/?q=dataset/elenco-enti-schedatori/resource/2a2975a4-4de1-448c-91cc-f1a1253be1bb

**Comment by anuzzolese** [comment]
Ciao Giorgio,

è interessante quello che proponi.
Essendo un CSV un linking in senso Linked Data non può essere fatto se il dataset non viene prima convertito in RDF.
Io propongo di usare il CSV per arricchire le informazioni che già produciamo utilizzando il codice ente come discriminante.
Ad esempio, nel nostro dataset l'individuo https://w3id.org/arco/resource/Agent/s37 corrisponde alla Soprintendenza Archeologia dell'Umbria. Quindi potremmo aggiungere un po' di proprietà (ex. nome, regione, ecc...) importandole da CSV.

Forse questo è quello che avevi in mente tu, giusto?

**Comment by ICCD-MiBACT** [comment]
Andrea si potrebbe ancora meglio convertire automaticamente , in fase di produzione dei dati, il codice ente con la denominazione dell'ente in chiaro presa dalla tabella in formato CSV che l'ICCD pubblica sul proprio  sito dei dati aperti.

**Comment by anuzzolese** [comment]
Intendi produrre la URI dell'individuo usando la denominazione dell'ente?

**Comment by giorgiobevilacqua** [comment]
Sì scusa intendevo proprio come dici tu: visto che si tratta di open data ICCD potrebbero essere triplificati e inclusi nel triplestore :-)
Se si decidesse di rendere l'URI espressivo, cmq sarebbe meglio non perdere l'informazione "s37" con cui si può al limite annotare l'ente schedatore.

**Comment by ICCD-MiBACT** [comment]
Io lascerei l'uri con il codice e la label e il name con la denominazione in chiaro

**Comment by anuzzolese** [comment]
Questa issue è stata risolta nella commit 083f29f
