### ISSUE TITLE
schiacciamento autori e identificativi locali

### ISSUE THREAD

**Issue by giorgiobevilacqua** [ICCD-MiBACT/ArCo#25]
Ciao,
ho notato che alcuni autori sono stati "schiacciati" anche se c'è un rischio di collisione tra identità diverse. Per esempio in questi due casi: 
- http://wit.istc.cnr.it/lodview/resource/Agent/fontana-pietro.html
- http://wit.istc.cnr.it/lodview/resource/Agent/audran-claude.html

Probabilmente, per ciascuno dei due casi, sono state schiacciate in un'unica entità persone che hanno lo stesso nome, ma che in realtà sono entità diverse (infatti sono presenti date di nascita e morte divergenti).
Cercando su Wikidata, si trovano diversi artisti con label "Claude Audran" vissuti nello stesso periodo:
- https://www.wikidata.org/wiki/Q8323299
- https://www.wikidata.org/wiki/Q5128686
- https://www.wikidata.org/wiki/Q669206 

Magari si tratta di un numero ridotto di casi ambigui, considerando tutto l'authority file ICCD. 
In ogni caso volevo chiedervi se nel lavoro di schiacciamento si è scelto volutamente un criterio non restrittivo, per evitare di generare troppi duplicati, oppure se si può ipotizzare di aggiungere qualche controllo in più, per esempio facendo un match parziale sulle date. Questo per capire come impostare un eventuale lavoro di interlinking a posteriori dell'authority file.

Inoltre, c'è un modo per tenere traccia dell'origine degli identificativi locali? Nel caso di Pietro Fontana per esempio ce ne sono molti, ma manca l'annotazione relativa all'authority file di provenienza (o forse sì, ma non trovo la query!).

Grazie,
Giorgio

**Comment by Valentina10** [comment]
Ciao Giorgio, sì, nella prima generazione dei dati sugli autori abbiamo utilizzato solo il nome (e l'eventuale specifica "attribuito", "bottega" etc. in casi particolari). Per l'update della seconda release, stiamo aggiungendo nell'URI anche il riferimento cronologico. Una nota che ritengo importante: questo riferimento è contenuto nel campo della normativa AUTA (attribuzione di autore preferita) e AATA (attribuzione di autore alternativa). Cito dalla normativa: "Fornire un riferimento cronologico. Per gli autori personali indicare le **date di nascita e di morte o, quando queste sono ignote, le date di attività**.". Da qui si deduce che la normativa lascia liberi i catalogatori riguardo a quali date inserire, se quelle di nascita o di morte o quelle di attività. In alcuni casi, poi, viene inserito anche del testo, come "notizie fino a...". Risulta quindi particolarmente complesso capire quando si tratta dello stesso autore e quando no. 

Per quanto riguarda gli identificativi locali (AUTH), non sono obbligatori, e abbiamo anche notato che autori diversi possono avere lo stesso identificativo: è una questione che approfondiremo con Chiara e Marialetizia. Nei dati non mi risulta che ci siano informazioni sulla provenienza degli identificativi, ma anche per questo potremmo cercare di capire se ci si può collegare agli authority files in cui sono contenuti.

**Comment by giorgiobevilacqua** [comment]
Ok grazie!
