### ISSUE TITLE
Pulizia sui dati: suggerimenti da valutare

### ISSUE THREAD

**Issue by ICCD-MiBACT** [ICCD-MiBACT/ArCo#27]
I campi valorizzati con "NR (recupero pregresso)" per motivi di compatibilità con le obbligatorietà previste dalle normative ICCD potrebbero non essere pubblicati in LOD (a meno che le obbligatorietà non siano previste anche nelle ontologie)

**Comment by Valentina10** [comment]
Sono d'accordo, penso abbia senso non pubblicare questi dati in LOD. Inseriremo nell'xslt i controlli necessari, in modo da evitare la generazione di risorse quando i campi siano valorizzati in quel modo.

Valentina
