### ISSUE TITLE
label ente schedatore

### ISSUE THREAD

**Issue by smazzini** [ICCD-MiBACT/ArCo#29]
Abbiamo notato che la label dell'ente schedatore è costituita da un codice, potete prevedere di utilizzare anche il nome?

**Comment by Valentina10** [comment]
Se n'è parlato qui, ma è ancora un "work in progress": https://github.com/ICCD-MiBACT/ArCo/issues/24

**Comment by anuzzolese** [comment]
Questa issue è stata risolta nella commit 083f29f
