### ISSUE TITLE
Report Gruppo Puglia

### ISSUE THREAD

**Issue by vitowalteranelli** [ICCD-MiBACT/ArCo#3]
Vorremmo modellare i dati relativi alle masserie di Puglia.
Non siamo riusciti a mappare sulle ontologie di Arco:
- Masseria che potrebbe essere una sottoclasse di luogo della cultura
- Opuscolo, Libretto d'opera, Copialettere etc.
- e alcune informazioni sulle risorse digitali 
      * per quanto riguarda i documenti:
            * l'argomento che può assumere i valori storia e tradizione, cinema, speccacoli e eventi etc. 
            * categoria (manifesto, fotobusta, catalogo)
            * soggetto (utilizziamo quando disponibile il nuovo soggettario di firenze)
     *  la licenza della risorsa digitale
     * formato della risorsa digitale
    * livello qualità della risorsa digitale (bassa/alta/media risoluzione)
    * detentore dei diritti e proprietà intellettuale
    * collezione digitale (che raggruppa una serie di risorse digitali) e identificativo della collezione
    * link alla scheda presente sulla digital library
- abito d'epoca (che ha delle risorse digitali a corredo)

**Comment by ValentinaCarriero** [comment]
Un piccolo chiarimento: tutte le informazioni elencate si riferiscono a dati di cui siete in possesso, ma che non sono ancora pubblicati in LOD? O nell'elenco sono menzionati anche dati che voi avete già pubblicato in LOD?

**Comment by paolamarzocca** [comment]
Buongiorno, i dati elencati sono già modellati e pubblicati in formato LOD, utilizzando altre ontologie. Vorremmo modellare gli stessi anche attraverso l'adozione dell'ontologia ArCo.
