### ISSUE TITLE
campi LDCM (OA) e COL (PST)

### ISSUE THREAD

**Issue by smazzini** [ICCD-MiBACT/ArCo#31]
sarebbe utile mappare questi due campi nell'ontologia (è il riferimento alla collezione)

**Comment by Valentina10** [comment]
UB/COL, che è anche un campo della Normativa Trasversale 4.00, è stato già modellato nel modulo subjective e sono state anche prodotte le regole nell'xslt. Provvederemo al più presto a mappare anche LDCM!
