### ISSUE TITLE
Campi relativi alla documentazione collegata

### ISSUE THREAD

**Issue by smazzini** [ICCD-MiBACT/ArCo#32]
Sono stati già prodotti dati relativi alla documentazione collegata?

**Comment by Valentina10** [comment]
Le regole le trovi nell'xslt, nel commit del 19 settembre https://github.com/ICCD-MiBACT/ArCo/commit/f347e295a85e06e81fb8b38d76b33209b104acbc
Queste regole sono state testate su un piccolo campione di schede, quindi possono contenere errori.
I dati relativi saranno presenti nella terza release, prevista a giorni.
