### ISSUE TITLE
ArCo-release/ontologie/objective/objective.owl Not Found: 404

### ISSUE THREAD

**Issue by TSScrooge** [ICCD-MiBACT/ArCo#33]
`Building virtuoso
Step 1/28 : FROM tenforce/virtuoso:1.3.1-virtuoso7.2.2
 ---> 6f55910ba50a
Step 2/28 : ADD https://raw.githubusercontent.com/ICCD-MiBACT/ArCo/master/ArCo-release/ontologie/objective/objective.owl /usr/local/virtuoso-opensource/share/virtuoso/vad/ontologies/
ERROR: Service 'virtuoso' failed to build: ADD failed: failed to GET https://raw.githubusercontent.com/ICCD-MiBACT/ArCo/master/ArCo-release/ontologie/objective/objective.owl with status 404 Not Found: 404: Not Found`

**Comment by Valentina10** [comment]
è stata appena rilasciata la release 0.3 di ArCo, adesso non dovrebbe avere più problemi con il docker, che erano dovuti ad aggiornamenti in corso!
