### ISSUE TITLE
Typed o Qualified TimeIndexedLocation?

### ISSUE THREAD

**Issue by giorgiobevilacqua** [ICCD-MiBACT/ArCo#34]
ciao! Penso che ci sia un typo nell'ontologia.

Nell'ontologia è indicata questa property (con typo credo):
https://w3id.org/arco/location/hasTimeIndexedQualifiedLocation

mentre l'endpoint risponde a questa property:
https://w3id.org/arco/location/hasTimeIndexedTypedLocation

(nell'ontologia, infatti, anche la Classe è indicata come "Typed" invece che "Qualified":
https://w3id.org/arco/location/TimeIndexedTypedLocation)

**Comment by Valentina10** [comment]
Grazie per la segnalazione! Abbiamo deciso di modificare qualified in typed perché la traduzione risultava più appropriata, provvedo subito a correggere il nome della proprietà nell'ontologia!
