### ISSUE TITLE
Object property mancante (collection ID)

### ISSUE THREAD

**Issue by FabDot-IO** [ICCD-MiBACT/ArCo#35]
La CQ 18: "Qual è il codice identificativo della collezione X? E quali beni ne fanno parte?" non ha possibilità di risoluzione. Non esiste un modo per descrivere un Identificativo per una Collezione.

**Comment by Valentina10** [comment]
Abbiamo creato una datatype "https://w3id.org/arco/ontology/context-description/collectionIdentifier" che puoi trovare nel file https://github.com/ICCD-MiBACT/ArCo/blob/master/ArCo-release/ontologie/context-description/context-description-v.0.2.owl
