### ISSUE TITLE
Competency Questions

### ISSUE THREAD

**Issue by FabDot-IO** [ICCD-MiBACT/ArCo#36]
Le seguenti domande hanno come output dati anomali:

38- Quali sono stati gli organizzatori degli eventi del bene x?
Risposta: "agent": { "type": "uri", "value": "https://w3id.org/arco/resource/Agent/true" }

39- Qual'è il tempo e il luogo di un esibizione che ha compreso il bene culturale x?
Risposta: "time-location": { "type": "literal", "value": "true" }

**Comment by Valentina10** [comment]
Grazie, c'era un errore nel file xslt, ho corretto. I dati della prossima release non dovrebbero più presentare questo errore!
