### ISSUE TITLE
Verifying Inferences (VI#08)

### ISSUE THREAD

**Issue by ValentinaPasqual** [ICCD-MiBACT/ArCo#37]
Le restrizioni della classe BiologicalTaxonomy (arco-context-description) sono "has concept only Genus",  "has concept only Species", "has concept only Subspecies". Per questo motivo l'assegnazione di un'entità ad una di quelle classi (Genus, Species, Subspecies) fa sì che il reasoner automaticamente assegni all'entità anche la tipologia delle altre due classi.

**Comment by Valentina10** [comment]
Per coerenza con le altre modellazioni, per le quali si prevede la specializzazione in sottoproprietà delle proprietà toplevel del modulo arco-core, questa issue è stata risolta (risoluzione da confermare dopo nuovo test) creando sottoproprietà di hasConcept, ovvero: arco-cd:hasGenus, arco-cd:hasSpecies, arco-cd:hasSubspecies
