### ISSUE TITLE
cleaning per gli agent

### ISSUE THREAD

**Issue by Valentina10** [ICCD-MiBACT/ArCo#38]
esempio di necessità entity-linking:

http://wit.istc.cnr.it/lodview/resource/CollectionOfCulturalEntities/apparecchiature-strumenti-e-accessori-mudif.html 
ha collegate tramite la proprietà arco-cd:hasCollector
queste due risorse: 
http://wit.istc.cnr.it/lodview/resource/Agent/associazione-culturale-il-didrammo.html 
e
http://wit.istc.cnr.it/lodview/resource/Agent/associazione-il-didrammo.html

**Comment by Valentina10** [comment]
esempio aggiornato:
1) http://dati.beniculturali.it/lodview-arco/resource/Agent/0b817db68ac6aa9102f8b057d9ae1474.html "Associazione Culturale IL DIDRAMMO"
2) http://dati.beniculturali.it/lodview-arco/resource/Agent/37dbed4aa6b268d43627480eaf5c43b4.html "Associazione IL DIDRAMMO"
3) http://dati.beniculturali.it/lodview-arco/resource/Agent/d8dc347e1a7d03ded4d37ff2907d55ad.html "Associazione Culturali Il Didrammo"

**Comment by luigi-asprino** [comment]
@Valentina10, pensandoci, forse questa potrebbe essere segnalata. 
Perchè la cosa migliore sarebbe avere una entità per tutte e tre le entry, non un linking tra le tre.
Per fare questo potremmo prevedere dei regole di ripulitura che ad esempio considerassero "Associazione Culturale"="Associazione"="Associazione Culturali"
Ma questo potrebbe creare casini altrove e non sarebbe una soluzione abbastanza sostenibile e abbastanza generica da applicarla ad altri casi. 
Quindi, penso che per garantire la qualità del dato, sia nel KG che alla fonte, la cosa migliore è segnalare la scheda. Che ne pensi?

**Comment by Valentina10** [comment]
sì, direi che ha senso!

**Comment by luigi-asprino** [comment]
ottimo allora chiudo la issue e recuperiamo le schede di origine
