### ISSUE TITLE
VI_12 & VI_17

### ISSUE THREAD

**Issue by FabDot-IO** [ICCD-MiBACT/ArCo#57]
- hasLegibility has Domain "ConservationStatus"
- hasLegibility is SubProperty of hasCulturalEntityCharacteristic
- hasCulturalEntityCharacteristic has Domain CulturalEntity
- hasLegibility inherits his ancestor's Domain, CulturalEntity

For that reason a ConservationStatus that hasLegibility becomes a CulturalEntity

**Comment by Valentina10** [comment]
This issue was solved with commit https://github.com/ICCD-MiBACT/ArCo/commit/b9f7e1220e21f67bd4145fd892eaa1d6d85971e2
