### ISSUE TITLE
abilitazione endpoint query federate

### ISSUE THREAD

**Issue by fguernaccini** [ICCD-MiBACT/ArCo#58]
Sarebbe molto utile che abilitaste l'endpoint alle query federate

**Comment by ICCD-MiBACT** [comment]
Tenete presente che l'endpoint in cui sono i dati di ArCO è assolutamente provvisorio. I dati saranno a breve pubblicati sull'endpoint ufficiale del MiBAC che è già abilitato alle query federate

**Comment by anuzzolese** [comment]
Utilizzando la clausola SERVICE all'interno di query SPARQL è possibile già fare query federate nell'attuale endpoint temporaneo.
