### ISSUE TITLE
QNT - normativa trasversale e scheda F

### ISSUE THREAD

**Issue by fguernaccini** [ICCD-MiBACT/ArCo#59]
I campi QNTN e QNTI sono mappati entrambi sia su arco:numberOfComponents che su arco:numberOfMembers, mentre QNTO (della scheda F) non è mappato.

**Comment by Valentina10** [comment]
QNTN e QNTI sono correttamente mappati sulle due proprietà, perché un ComplexCulturalProperty può essere rappresentato sia come insieme di componenti sia come insieme di membri (cioè come collection). Il campo QNTO è stato momentaneamente lasciato fuori dalla release 1.0, gli daremo alta priorità tra la cose da modellare nella prossima release.

**Comment by fguernaccini** [comment]
Ciao Valentina, vorrei chiederti un chiarimento usando un esempio: http://dati.beniculturali.it/lodview-arco/resource/HistoricOrArtisticProperty/1200144955-0.html
Il valore di https://w3id.org/arco/ontology/arco/numberOfComponents è 26, ma come faccio a sapere se proviene da QNTI o QNTN? Cioè, se io volessi fare il procedimento inverso da LOD a dato come da scheda ICCD, con quale criterio automatico posso ricollocare il dato nel campo esatto? So che QNTI e QNTN non possono coesistere, forse potrei basarmi sul valore di https://w3id.org/arco/ontology/arco/hasCulturalPropertyCataloguingCategory?

**Comment by Valentina10** [comment]
Grazie all'aiuto di Maria Letizia Mancinelli (ICCD), posso intanto chiarire che i due campi QNTI e QNTN possono essere entrambi compilati, come da esempio:
OGTD: scatola entomologica
QNTN: 4 [= serie composta da quattro esemplari di scatole entomologiche, ognuna delle quali contiene 50 insetti]
QNTI: 200 [numero complessivo degli insetti contenuti nella serie di scatole entomologiche]

A maggior ragione, come segnali tu, diventa rilevante distinguere i due valori. Prevederemo nella prossima release due proprietà separate per risolvere questo problema. Grazie!

**Comment by margherita-porena** [comment]
La suddivisione dei campi QNTI e QNTN è stata modellata rispettivamente con le seguenti DP:
https://w3id.org/arco/ontology/arco/numberOfElements
https://w3id.org/arco/ontology/arco/numberOfComponents

è stato modellato anche il campo QNTO con la DP https://w3id.org/arco/ontology/arco/positionInSequence
