### ISSUE TITLE
OGC - Trattamento catalografico (normativa trasversale e scheda F)

### ISSUE THREAD

**Issue by fguernaccini** [ICCD-MiBACT/ArCo#60]
Il campo OGCT non è mappato per le schede in oggetto. E' stato mappato solamente il campo OGCT della scheda AT che però ha un'accezione diversa (contesto)

**Comment by Valentina10** [comment]
Il campo OGCT per normative diverse dalla AT verrà sicuramente incluso nella prossima release, grazie per la segnalazione.

**Comment by margherita-porena** [comment]
Nel commit: 43e0fdaadb62cd5162beb2474ddaf401e72a9b62 è stato rappresentato il campo nell'xslt e la modifica è stata testata nella scheda F-4-00-ICCD12270243.xml
