### ISSUE TITLE
proliferazione cis:Site

### ISSUE THREAD

**Issue by fguernaccini** [ICCD-MiBACT/ArCo#62]
Da questa risorsa http://dati.beniculturali.it/lodview-arco/resource/MonumentalArea/musei-nazionali-di-lucca.html, nelle inverse risultano 33 Museo Nazionale di Villa Guinigi.
Questo è un altro esempio: http://dati.beniculturali.it/lodview-arco/resource/MonumentalArea/terme-di-diocleziano-complesso-della-certosa.html

**Comment by giorgiobevilacqua** [comment]
@anuzzolese ci sono aggiornamenti su questo fronte?
Stiamo lavorando all'interlinking dei Luoghi della Cultura e ci sarebbe utile sapere se è in programma un lavoro di data quality su questo tipo di entità.

Qui una query che evidenzia la presenza cis:Site duplicati:

http://wit.istc.cnr.it/arco/virtuoso/sparql?default-graph-uri=&query=select+distinct+%3Fsite+%3Flabel+where+%7B%0D%0A++%3FtimeIndexedLocation+%3Chttps%3A%2F%2Fw3id.org%2Farco%2Fontology%2Flocation%2FatSite%3E+%3Fsite+.%0D%0A++%3Fitem+%3Chttps%3A%2F%2Fw3id.org%2Farco%2Fontology%2Flocation%2FhasTimeIndexedTypedLocation%3E+%3FtimeIndexedLocation+.%0D%0A++%3Fsite+rdfs%3Alabel+%3Flabel%0D%0A%7D%0D%0AORDER+BY+%3Flabel&should-sponge=&format=text%2Fhtml&timeout=0&debug=on  

Grazie!

**Comment by luigi-asprino** [comment]
Ciao,

abbiamo generato una nuova versione del dataset (id 1.0.1), mantenendo la vecchia sempre attiva.
E' interrogabile da questo [endpoint](http://etna.istc.cnr.it/arco-pr/virtuoso/sparql)
Essendo una pre-release la dereferenziazione degli URI non è attiva (lodview).
Ci sono ancora delle site duplicati.
In particolare lanciando questa [query](http://etna.istc.cnr.it/arco-pr/virtuoso/sparql?default-graph-uri=&query=select+distinct+%3Fs+%3Fl+%7B%0D%0A%3Fs+%3Chttp%3A%2F%2Fdati.beniculturali.it%2Fcis%2FisPartOf%3E+%3Chttps%3A%2F%2Fw3id.org%2Farco%2Fresource%2FMonumentalArea%2Fmusei-nazionali-di-lucca%3E+.+%0D%0A%3Fs+%3Fp+%3Fo+.+%0D%0A%3Fs+%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23label%3E+%3Fl+%7D&format=text%2Fhtml&timeout=0&debug=on&run=+Run+Query+)

```
select distinct ?s ?l {
?s <http://dati.beniculturali.it/cis/isPartOf> <https://w3id.org/arco/resource/MonumentalArea/musei-nazionali-di-lucca> . 
?s ?p ?o . 
?s <http://www.w3.org/2000/01/rdf-schema#label> ?l }
```
 si ottengono 4 risultati (erano 33).

@Valentina10  ha fatto ulteriori correzioni per risolvere la issue #68 , e stiamo ri-generando il dataset.

**Comment by luigi-asprino** [comment]
I problemi evidenziati per le risorse derivano tutti da errori di digitazione presenti nelle schede di origine.
Abbiamo segnalato le schede all'ICCD, così da permettere una correzione dell'errore alla fonte.
La correzione sarà quindi effettiva nella prossima release.
Grazie per la segnalazione.
Chiudo la issue.
