### ISSUE TITLE
campo RO/ROF/ROFA

### ISSUE THREAD

**Issue by fguernaccini** [ICCD-MiBACT/ArCo#63]
E' prevista nella prossima release la mappatura di questo campo? Non è presente nella normativa trasversale, ma è sicuramente presente nelle schede OA, S e PST, sarebbe molto utile perché definisce il rapporto opera finale/originale

**Comment by Valentina10** [comment]
Ciao, riguardando l'xslt mi risulta mappato, con la proprietà a-cd:hasAuthor
dove hai verificato che non c'è?

**Comment by fguernaccini** [comment]
Ciao Valentina, qui https://github.com/ICCD-MiBACT/ArCo/blob/master/ArCo-release/ontologie/context-description/context-description.owl

**Comment by Valentina10** [comment]
Intendi dire che non è annotato da nessuna parte come valore di "a-cat:iccdNormTag"? Deve essere sfuggito, andrebbe annotato su a-cd:hasAuthor. In ogni caso, non riusciamo a garantire copertura totale in quelle annotazioni, considerata l'estrema varietà tra le normative, anche se naturalmente cerchiamo, ogni volta che si presenta un campo nuovo da mappare su una proprietà/classe già esistente, di annotarlo. 

I dati ci sono, puoi vederli con questa query:

PREFIX a-cd: <https://w3id.org/arco/ontology/context-description/>
SELECT DISTINCT ?e2, ?e3, ?e4
WHERE
{?e1 a-cd:hasRelatedWorkSituation ?e2 . ?e2 a-cd:involvesRelatedWork ?e3 . ?e3 a-cd:hasAuthor ?e4 .}
LIMIT 100

**Comment by luigi-asprino** [comment]
c'è ancora questo problema?

**Comment by Valentina10** [comment]
La issue può essere considerata come risolta: nella prossima release sarà annotato nell'ontologia il tag ROFA, mentre i dati relativi sono già presenti nella release attuale.

**Comment by luigi-asprino** [comment]
Chiudo allora
