### ISSUE TITLE
Versionamento Ontologie

### ISSUE THREAD

**Issue by luigi-asprino** [ICCD-MiBACT/ArCo#65]
Bisogna adottare una politica di versionamento delle ontologie.
Per iniziare proporrei di fare una politica come quella di OntoPiA.
La versione attuale della network diventa la versione 0.5 
Che ne dite? @anuzzolese @Valentina10 
Ci sono regole di ridirezione che puntano ai raw di GitHub?

**Comment by Valentina10** [comment]
La versione attuale sarebbe la 1.0, in realtà! I PURL reindirizzano alla visualizzazione HTML dei raw di GitHub, per esempio https://w3id.org/arco/ontology/arco punta su http://dati.beniculturali.it/lode/extract?url=https://raw.githubusercontent.com/ICCD-MiBACT/ArCo/master/ArCo-release/ontologie/arco/arco.owl

**Comment by luigi-asprino** [comment]
Allora si potrebbero lasciare questi file come latest version (così non bisogna cambiare le regole di ridirezione almeno per ora), provo a farlo.

**Comment by luigi-asprino** [comment]
pensavo ad una cosa del genere
