### ISSUE TITLE
Dati ridondanti maiuscole nelle label

### ISSUE THREAD

**Issue by br0ast** [ICCD-MiBACT/ArCo#67]
Ho notato tramite alcune query che molti elementi hanno una triplice "rdfs:label" ( Iniziale minuscola MAIUSCOLA) delle volte ripetuto anche tramite l'annotazione "l0:name"

es: http://dati.beniculturali.it/lodview-arco/resource/Region/toscana.html

Tramite un'omologazione di questi label si potrebbe alleggerire il dataset.

**Comment by luigi-asprino** [comment]
Con la release 1.0.2, disponibile in pre-release su questo [endpoint](http://etna.istc.cnr.it/arco-pr/virtuoso/sparql) è stato risolto questo problema 

```
select distinct ?l {
   <https://w3id.org/arco/resource/Region/toscana> rdfs:label ?l
}
```

qui i [risultati](http://etna.istc.cnr.it/arco-pr/virtuoso/sparql?default-graph-uri=&query=select+distinct+%3Fl+%7B%0D%0A+++%3Chttps%3A%2F%2Fw3id.org%2Farco%2Fresource%2FRegion%2Ftoscana%3E+rdfs%3Alabel+%3Fl%0D%0A%7D&format=text%2Fhtml&timeout=0&debug=on&run=+Run+Query+)
