### ISSUE TITLE
Luoghi della Cultura: schiacciamento di entità diverse

### ISSUE THREAD

**Issue by giorgiobevilacqua** [ICCD-MiBACT/ArCo#68]
ciao, ho notato che in alcuni casi le entità che corrispondono ai Luoghi della Cultura (<http://dati.beniculturali.it/cis/CulturalInstituteOrSite> ) sono state schiacciate tra di loro anche se si riferiscono a entità diverse (pur avendo la stessa label). L'informazione relativa all'univocità del Luogo della Cultura potrebbe essere dedotta dal <http://dati.beniculturali.it/cis/Site> che è collegato al Luogo. Ad esempio, qui la lista dei diversi Site (e indirizzi dei Site) che sono collegati a <https://w3id.org/arco/resource/CulturalInstituteOrSite/museo-archeologico-nazionale>:

```
select distinct ?SiteLabel ?SiteAddress where {
<https://w3id.org/arco/resource/CulturalInstituteOrSite/museo-archeologico-nazionale> <http://dati.beniculturali.it/cis/hasSite> ?Site .
?Site rdfs:label ?SiteLabel .
?Site <http://dati.beniculturali.it/cis/siteAddress>  ?SiteAddressURI .
?SiteAddressURI rdfs:label ?SiteAddress .
}
order by ?SiteLabel
```

In sintesi, sarebbe utile scorporare l'entità museo-archeologico-nazionale in entità diverse, a seconda delle informazioni contenute nel Site a cui sono collegate.

**Comment by Valentina10** [comment]
Ciao Giorgio, grazie per la segnalazione, provvediamo a modificare le URI dei CulturalInstituteOrSite aggiungendo le informazioni sull'indirizzo collegate al Site e producendo un codice univoco al posto della stringa!

**Comment by luigi-asprino** [comment]
La issue è stata risolta nella release 1.0.2 disponibile su questo [endpoint](http://etna.istc.cnr.it/arco-pr/virtuoso/sparql)
