### ISSUE TITLE
http://purl.org/net/provenance/ns#DataItem

### ISSUE THREAD

**Issue by fguernaccini** [ICCD-MiBACT/ArCo#69]
Ciao,
è previsto l'inserimento di http://purl.org/net/provenance/ns#DataItem per fornire informazioni su creazione e aggiornamento delle risorse?

**Comment by luigi-asprino** [comment]
Ciao, 
ti faccio qualche domanda per capire meglio.
Quale informazioni vorresti che sia presente? 
A che livello vorresti inserire l'informazione di provenance? A livello di singola risorsa RDF? A livello di grafo?

**Comment by fguernaccini** [comment]
Ciao Luigi,
l'informazione essenziale è la data/ora di modifica a livello di singola tripla.
Ciao,
Fabiana

**Comment by margherita-porena** [comment]
The issue has been closed with commit a3a2d74
