### ISSUE TITLE
Allineamento dati scheda RA col Thesaurus SKOS RA

### ISSUE THREAD

**Issue by ICCD-MiBACT** [ICCD-MiBACT/ArCo#7]
Si potrebbe fare un allineamento, laddove possibile del campo OGTD  della Scheda RA – Reperti Archeologici con gli skos:Concept del Thesaurus RA disponibile sul sito http://dati.beniculturali.it e indicizzato sull'endpoint

**Comment by ValentinaCarriero** [comment]
Il Thesaurus riguarda solo i possibili valori del campo OGTD, o anche quelli del campo OGTT?

**Comment by MiBACT-LinkedOpenData** [comment]
Ciao,
come si legge nell'introduzione al thesaurus (http://www.iccd.beniculturali.it/index.php?it/473/standard-catalografici/Standard/74), in particolare nel documento http://www.iccd.beniculturali.it/getFile.php?id=4089  nella tabella a pagina 3, le prime tre colonne del thesaurus (per il momento applicato solo per la RA 3.00) vengono utilizzate per valorizzare il campo CLS della RA e le colonne 4 e 5 per il sottocampo OGTD (OGTT, infatti, nella RA 3.00 viene utilizzato per la citazione di classificazioni sulla base di repertori).
Quando rilasceremo la versione 4.00 della RA, invece, il thesaurus potrà essere applicato come segue:
 PARAGRAFO OG 4.00
CTG	Categoria	                livelli 1-2-3 
OGT	DEFINIZIONE BENE	 
OGTD	Definizione 	        livello 4
OGTT	Tipologia 	        livello 5 (funzione e morfologia) 
OGTW	Parte residuale	livello 5 (parte) 
OGTP	Parte componente	 
OGTS	Classificazione/repertorio	(qui verrà mappato il valore di OGTT della RA 3.00) 
OGTV	Configurazione strutturale e di contesto

**Comment by Valentina10** [comment]
Questa issue è stata risolta con la commit https://github.com/ICCD-MiBACT/ArCo/commit/4dd032f30a4a92934c5e09fc2614dfeb4f6845cc
