### ISSUE TITLE
Segnalazione a-cd:isCollectorOf

### ISSUE THREAD

**Issue by fguernaccini** [ICCD-MiBACT/ArCo#70]
Ciao,
segnalo che la object property <https://w3id.org/arco/ontology/context-description/isCollectorOf>, nei dati ha come range dei literal

select * where {?s <https://w3id.org/arco/ontology/context-description/isCollectorOf> ?o}

**Comment by Valentina10** [comment]
Ciao, me n'ero accorta giusto tre giorni fa, e infatti nel commit https://github.com/ICCD-MiBACT/ArCo/commit/2169b6f781e9b021744811abcbc399a6351f06cf ho modificato quelle righe dell'xslt. Appena riprodurremo i dati non ci sarà più questo errore!

Valentina
