### ISSUE TITLE
 relazione tra bene complesso e componente

### ISSUE THREAD

**Issue by fguernaccini** [ICCD-MiBACT/ArCo#71]
Ciao,
non è presente la relazione tra bene complesso e componente, ad esempio questi due beni dovrebbero avere un legame (lo si vede dal SIGEC)
http://dati.beniculturali.it/lodview-arco/resource/ArchitecturalOrLandscapeHeritage/1100222178-bene-complesso.html
http://dati.beniculturali.it/lodview-arco/resource/ArchitecturalOrLandscapeHeritage/1100222179-bene-componente.html

**Comment by Valentina10** [comment]
Ciao, finora gestivamo la relazione solo per le normative di versione 4.00. Abbiamo guardato le schede relative ai due beni di esempio (di tipo A versione 2.00), e individuato un campo che potrebbe essere usato come "chiave" per creare la relazione tra le due risorse. Tuttavia, nella maggior parte delle normative il campo ha un nome diverso da quello che si trova nelle prime due versioni della normativa A, e guardando qualche esempio sembra essere compilato in maniera non sempre coerente. Ci serve quindi un po' di tempo per studiare i vari casi ed eventuali errori nei dati e capire come gestire le regole di trasformazione, vi teniamo aggiornati!

**Comment by margherita-porena** [comment]
The issue has been closed with commit d4d3931
