### ISSUE TITLE
molteplicità schede/*/RE/RCG/RCGA (scientific-director)

### ISSUE THREAD

**Issue by oibaf** [ICCD-MiBACT/ArCo#72]
arco.xslt revision 886

Type error at char 38 in xsl:value-of/@select on line 10021 column 67
  XPTY0004: A sequence of more than one item is not allowed as the first argument of
  arcofy() ("di Gennaro, Francesco", "Pacciarelli, Marco")
net.sf.saxon.s9api.SaxonApiException: A sequence of more than one item is not allowed as the first argument of arcofy()

[offendingNode.zip](https://github.com/ICCD-MiBACT/ArCo/files/4458248/offendingNode.zip)

**Comment by luigi-asprino** [comment]
Grazie per la segnalazione.
Risolto con il commit 908882fb293a8aac799d2341c1b30114c63e7850

**Comment by oibaf** [comment]
grazie per la correzione! dovrebbe risolvere almeno altri 34 casi analoghi (sui dati dati attualmente esposti su oai-pmh, ma la scansione è ancora in corso...)
