### ISSUE TITLE
caratteri speciali in regex literal (SKOSThesaurusLinker)

### ISSUE THREAD

**Issue by oibaf** [ICCD-MiBACT/ArCo#73]
il dato in RA/OG/OGT/OGTD/ è probabilmente anomalo in questo caso (xml allegato), ma l'utilizzo della espressione regolare nel filtro della query in SKOSThesaurusLinker causa un errore per la presenza di caratteri speciali (dovrebbe bastare un confronto "case insensitive" però)

[node+stack_trace.zip](https://github.com/ICCD-MiBACT/ArCo/files/4464147/node%2Bstack_trace.zip)

**Comment by luigi-asprino** [comment]
Grazie per la segnalazione
Ho aggiunto un passo di pulizia degli argomenti nello SKOSThesaurusLinker.
Risolto con commit 1798c33374c6965997d8a8d3d74a038e369513ef

**Comment by oibaf** [comment]
grazie, analogo a 1600015665
