### ISSUE TITLE
RelatedWorkSituation (RV/ROZ)

### ISSUE THREAD

**Issue by oibaf** [ICCD-MiBACT/ArCo#74]
il collegamento fra il bene culturale e la relazione con il bene collegato (ad esempio [scheda](http://catalogo.beniculturali.it/oaitarget/OAIHandler?verb=GetRecord&metadataPrefix=oai_dc&identifier=oai:oaicat.iccd.org:@ICCD3902917@/xml/cards), [bene](https://w3id.org/arco/resource/HistoricOrArtisticProperty/1500068123), [collegamento](https://w3id.org/arco/resource/RelatedWorkSituation/1500068123-related-cultural-property-2-1)) è assente

**Comment by luigi-asprino** [comment]
Grazie per la segnalazione.

Faccio qualche domanda per capire meglio.

Potrebbe farmi qualche esempio esempio concreto? Prendo come esempio qualche scheda magari.
E' un qualcosa che secondo lei manca nei dati o nell'ontologia o in entrambi?
Quali sono i dati che vorrebbe vedere? O meglio quali sono le interrogazioni che vorrebbe fare sui dati?

**Comment by oibaf** [comment]
certo, scusa la sintesi, con i collegamenti dei collegamenti devo aver fatto confusione...

la scheda xml nell'esempio 1500068123 contiene in RV/ROZ il riferimento a 1500068163

negli rdf generati c'è il bene https://w3id.org/arco/resource/HistoricOrArtisticProperty/1500068123 e l'oggetto che crea correttamente il collegamento con 1500068163 https://w3id.org/arco/resource/RelatedWorkSituation/1500068123-related-cultural-property-2-1

quest'ultimo però risulta orfano, nel senso che l'unico riferimento al bene che l'ha originato è nella parte testuale, ma non c'è una data property diretta o inversa fra i due (probabilmente manca hasRelatedWorkSituation sul bene)

ho allegato i file xml

grazie!

**Comment by oibaf** [comment]
l'allegato! [ICCD3902917.zip](https://github.com/ICCD-MiBACT/ArCo/files/4489390/ICCD3902917.zip)

**Comment by luigi-asprino** [comment]
Quindi, mi sembra che il problema sia la mancanza di questa tripla

```
<https://w3id.org/arco/resource/RelatedWorkSituation/1500068123-related-cultural-property-2-1> <https://w3id.org/arco/ontology/context-description/isRelatedWorkSituationOf> <https://w3id.org/arco/resource/HistoricOrArtisticProperty/1500068123> .
```

**Comment by oibaf** [comment]
oppure questa

`<https://w3id.org/arco/resource/HistoricOrArtisticProperty/1500068123> <https://w3id.org/arco/ontology/context-description/hasRelatedWorkSituation> <https://w3id.org/arco/resource/RelatedWorkSituation/1500068123-related-cultural-property-2-1> .
`

o entrambe, ma tra le due eviterei l'inversa, il problema è che con i dati attuali non è possibile selezionare tutto ciò che pertiene al bene...

**Comment by luigi-asprino** [comment]
Le ho aggiunte entrambe.

Risolto con commit fc036804c5245c738af65193801c04856ba1a633

**Comment by oibaf** [comment]
grazie!
