### ISSUE TITLE
AUTN e AUFN

### ISSUE THREAD

**Issue by luigi-asprino** [ICCD-MiBACT/ArCo#78]
**Indicare quali parti del progetto sono coinvolte nel bug: ontologia, knowledge graph, rdfizer**

rdfizer

**Descrivere il problema**

Issue derivata da [un commento alla issue 75](https://github.com/ICCD-MiBACT/ArCo/issues/75#issuecomment-627169202) di @oibaf

Sembra che alcune schede diano problemi per la trasformazione dei campi AUTN e AUFN causando il seguente errore di RDFizer

```
Type error at char 43 in xsl:value-of/@select on line 601 column 65 XPTY0004: An empty sequence is not allowed as the first argument of arcofy() net.sf.saxon.s9api.SaxonApiException: An empty sequence is not allowed as the first argument of arcofy() at net.sf.saxon.s9api.XsltTransformer.transform(XsltTransformer.java:606) at it.cnr.istc.stlab.arco.Converter.convert(Converter.java:294)
```

**Descrivere come riprodurre il problema**

Trasformazione scheda ICCD11143519

**Comportamento atteso**

Trasformazione senza errrore

**Informazioni aggiuntive**

**Comment by Valentina10** [comment]
This issue has been solved with commit https://github.com/ICCD-MiBACT/ArCo/commit/3c95276734a7e72ef68b017a3c25289aa9cb05b4

**Comment by oibaf** [comment]
grazie, il problema con AUTN sembra risolto, c'è ancora il caso AUFN però

`Type error at char 38 in xsl:value-of/@select on line 633 column 65
  XPTY0004: An empty sequence is not allowed as the first argument of arcofy()
net.sf.saxon.s9api.SaxonApiException: An empty sequence is not allowed as the first argument of arcofy()
        at net.sf.saxon.s9api.XsltTransformer.transform(XsltTransformer.java:606)
        at it.cnr.istc.stlab.arco.Converter.convert(Converter.java:294)`

ad esempio ICCD11688223 o ICCD11689708 (al momento non pubblicate su oai da quando è attivo l'ambiente di test)

**Comment by Valentina10** [comment]
grazie, adesso col commit  https://github.com/ICCD-MiBACT/ArCo/commit/f10536be8176da776bf36f3ffebcee47f6de3ae3 non dà più errore sulle due schede, se mi è sfuggito altro me lo segnali pure!
