### ISSUE TITLE
URI Affixed Element

### ISSUE THREAD

**Issue by luigi-asprino** [ICCD-MiBACT/ArCo#80]
**Indicare quali parti del progetto sono coinvolte nel bug: ontologia, knowledge graph, rdfizer**

rdfizer

**Descrivere il problema**

Issue derivata da [un commento alla issue 75](https://github.com/ICCD-MiBACT/ArCo/issues/75#issuecomment-627169202) di @oibaf

Nella generazione della scheda ICCD13670494 la URI

- ``https://w3id.org/arco/resource/AffixedElement/1500391452-affixed-element-1``

Non viene usata mai come soggetto delle triple

**Descrivere come riprodurre il problema**

Generare con rdfizer le triple relative alla scheda ICCD13670494

**Comportamento atteso**

La URI ``https://w3id.org/arco/resource/AffixedElement/1500391452-affixed-element-1`` compaia come soggetto nelle triple generate dalla scheda ICCD13670494

**Informazioni aggiuntive**

**Comment by Valentina10** [comment]
This issue has been solved with commit https://github.com/ICCD-MiBACT/ArCo/commit/4ce1fc733390995cf7b57421db488e7a3a855f4a
