### ISSUE TITLE
URI Alternative Autorship Attribution

### ISSUE THREAD

**Issue by luigi-asprino** [ICCD-MiBACT/ArCo#81]
**Indicare quali parti del progetto sono coinvolte nel bug: ontologia, knowledge graph, rdfizer**

rdfizer

**Descrivere il problema**

Issue derivata da [un commento alla issue 75](https://github.com/ICCD-MiBACT/ArCo/issues/75#issuecomment-627169202) di @oibaf

Nella generazione della scheda ICCD5061694 le risorse 

- ``https://w3id.org/arco/resource/AlternativeAuthorshipAttribution/0900293025-1``

vengono usate come oggetto ma non sono usate mai come soggetto delle triple generate.

**Descrivere come riprodurre il problema**

Generare le triple per la scheda ICCD5061694 

**Comportamento atteso**

Le risorse siano soggetto di altre triple.

**Informazioni aggiuntive**

**Comment by margherita-porena** [comment]
This issue has been solved with commit 0dbd4bc
