### ISSUE TITLE
Tipo agenti

### ISSUE THREAD

**Issue by luigi-asprino** [ICCD-MiBACT/ArCo#82]
**Indicare quali parti del progetto sono coinvolte nel bug: ontologia, knowledge graph, rdfizer**

rdfizer

**Descrivere il problema**

Issue derivata da [un commento alla issue 75](https://github.com/ICCD-MiBACT/ArCo/issues/75#issuecomment-627169202) di @oibaf

Nella generazione della scheda ICCD5537718 la risorsa

- ``https://w3id.org/arco/resource/Agent/0700025094-user-1``

non ha type

**Descrivere come riprodurre il problema**

Generare le triple per la scheda ICCD5537718 

**Comportamento atteso**

Che la risorsa abbia tipo Agent secondo come indicato dall'ontologia

**Informazioni aggiuntive**

**Comment by margherita-porena** [comment]
This issue has been solved with commit db8e68e
