### ISSUE TITLE
URI Title

### ISSUE THREAD

**Issue by luigi-asprino** [ICCD-MiBACT/ArCo#83]
**Indicare quali parti del progetto sono coinvolte nel bug: ontologia, knowledge graph, rdfizer**

rdfizer

**Descrivere il problema**

Issue derivata da [un commento alla issue 75](https://github.com/ICCD-MiBACT/ArCo/issues/75#issuecomment-627169202) di @oibaf

Nella generazione della scheda ICCD4380149 le risorse 

- ``https://w3id.org/arco/resource/Title/0700103706-semipila-cum-eodem-ornatu``

vengono usate come oggetto ma non sono usate mai come soggetto delle triple generate.

**Descrivere come riprodurre il problema**

ICCD4380149

**Comportamento atteso**

Le risorse siano soggetto di altre triple.

**Informazioni aggiuntive**

**Comment by Valentina10** [comment]
This issue has been solved with commit https://github.com/ICCD-MiBACT/ArCo/commit/18c5a26fce11244d46ef10e22c45452fa33deff9
