### ISSUE TITLE
Dall'utente Lia (Stendhapp)

### ISSUE THREAD

**Issue by ICCD-MiBACT** [ICCD-MiBACT/ArCo#84]
Le allego un file in cui ho riassunto i beni di cui ci servirebbero le informazioni: in pratica sono i Beni Archeologici e i Beni Architettonici e Paesaggistici, così come descritti nelle categorie del vecchio sito ICCD. 
 
Ci servirebbero inoltre informazioni simili per gli eventi, così come sono descritti nel DB Unico: mostre ecc.
 
Nel file ho evidenziato le informazioni minime che ci servono per poter includere il bene  o l'evento nel nostro DB; le info nelle celle con sfondo colorato sono essenziali, mentre per la geolocalizzazione ci basta un'informazione a scelta tra l'indirizzo e le coordinate geografiche (se abbiamo tutti e due, meglio!). Per il resto, più informazioni abbiamo meglio è! 
 
Se le informazioni che vi ho chiesto vengono estratte con query SPARQL, mi sarebbe anche molto utile avere il testo della query, in modo da studiarmi bene la sintassi e le relazioni tra le ontologie "da dentro".
 
 
[TEMPLATE RICHIESTA DATI Punti ed Eventi.xlsx](https://github.com/ICCD-MiBACT/ArCo/files/4645255/TEMPLATE.RICHIESTA.DATI.Punti.ed.Eventi.xlsx)

**Comment by luigi-asprino** [comment]
Le informazioni richieste verranno aggiunte nella documentazione della prossima release
