### ISSUE TITLE
THSD scheda F (indicizzazione del soggetto)

### ISSUE THREAD

**Issue by fguernaccini** [ICCD-MiBACT/ArCo#85]
Segnalo che il campo THSD non risulta mappato, è un campo per la classificazione del soggetto della fotografia

**Comment by margherita-porena** [comment]
Il campo THSD verrà sicuramente incluso nella prossima release, grazie per la segnalazione.

**Comment by margherita-porena** [comment]
The issue has been solved with commit b2d3ab9
