### ISSUE TITLE
Mapping scheda E

### ISSUE THREAD

**Issue by ICCD-MiBACT** [ICCD-MiBACT/ArCo#86]
I campi della scheda E-Etnologia  sono stati mappati? 
Si tratta di una "vecchia BDM" specificamente progettata dalla Soprintendenza al Museo Nazionale Preistorico Etnografico “L. Pigorini”, di concerto con ICCD, per la catalogazione dei beni demoetnoantropologici materiali extra-europei

Le schede sono pubblicate.

**Comment by margherita-porena** [comment]
La maggior parte dei campi è mappata, mancano solo alcuni campi molto specifici (i campi del paragrafo RP) che saranno modellati nelle prossime release.

**Comment by margherita-porena** [comment]
Dato che la scheda è obsoleta, su consiglio di ICCD è stato deciso di non creare regole di trasformazione per i campi che non sono mai stati compilati dai catalogatori (tra cui il paragrafo RP) e per i quali, quindi, non ci sarebbero comunque dati.
Tutti i campi utilizzati nella scheda E risultano pertanto modellati.
