### ISSUE TITLE
Beni numismatici - classificazione

### ISSUE THREAD

**Issue by ICCD-MiBACT** [ICCD-MiBACT/ArCo#88]
Per quanto riguarda i beni numismatici la classificazione "classica" è quella espressa in OGTT (vedi anche l'introduzione alla normativa).
Ma per gli oggetti che non sono propriamente monete, come i premonetali e i paramonetali, è utile avere la classificazione funzionale (in genere non presente per le monete, la cui funzione è sottintesa): cfr. norme di compilazione del sottocampo OGTH.

Per quanto riguarda le mappature per ArCo: considerare entrambe le classificazioni, qualificandole (classificazione tipologica e classificazione funzionale), in modo da coprire tutte le situazioni

**Comment by margherita-porena** [comment]
The issue has been solved with commit c4716dd
