### ISSUE TITLE
Schiacciamento voci di autore errata

### ISSUE THREAD

**Issue by ICCD-MiBACT** [ICCD-MiBACT/ArCo#89]
Lo schiacciamento su un’unica entità degli autori pare basata solo sul nome e non anche sulle date. Qui sono chiaramente due autori diversi: Fontana Giovanni
![Fontana](https://user-images.githubusercontent.com/34236512/83236056-2dddda80-a193-11ea-8f61-798180e671d8.png)

Potete verificare a cosa è dovuto l'errore?

**Comment by margherita-porena** [comment]
The issue has been solved with commit a7694c7
