### ISSUE TITLE
Implementazione RDFsizer per leggere ulteriori tag su schede ed entità multimediali

### ISSUE THREAD

**Issue by ICCD-MiBACT** [ICCD-MiBACT/ArCo#90]
Nel file XML generato dall'harvesting sono intervenute le seguenti modifiche che vanno implementate anche nel modulo RDFsizer:
1)	Alla fine delle schede di Catalogo, un tag harvesting segnala la presenza del geocoding (vedi ad esempio: http://catalogo.beniculturali.it/oaitarget/OAIHandler?verb=GetRecord&metadataPrefix=oai_dc&identifier=oai:oaicat.iccd.org:@ICCD14450442@/xml)
2)	Alla fine delle schede EMM (entità multimediale) un tag harvesting segnala l’URL completa delle immagini (vedi ad esempio: http://catalogo.beniculturali.it/oaitarget/OAIHandler?verb=ListRecords&resumptionToken=1591189459094:0:oai_dc:20200601000000:20200603235959:null/entita_multimediale)
Ora l’harvesting punta ad un DB di Test per cui queste modifiche sono visibili solo per i (pochi) record modificati dopo il 1 giugno.

**Comment by margherita-porena** [comment]
The issue has been closed with commit 93e8918
