### ISSUE TITLE
Label doppie/triple di autore senza prefLabel

### ISSUE THREAD

**Issue by ICCD-MiBACT** [ICCD-MiBACT/ArCo#93]
Occorre disambiguare quale è la label preferita per gli autori, perchè a livello applicativo si generano problemi.
Vedi ad esempio: http://dati.beniculturali.it/lodview-arco/resource/Agent/01da399dfad68380fc7aa9989e1f3fe3.html

Quale è il nome ufficiale?

Dovrebbe essere quello composto con cognome nome

**Comment by margherita-porena** [comment]
The issue has been closed with commit 6fcd5ed
