### ISSUE TITLE
campi BIBA e BIBD

### ISSUE THREAD

**Issue by fguernaccini** [ICCD-MiBACT/ArCo#94]
Ciao,
non sono state trasformate in LOD le informazioni relative a autore e data della bibliografia. Di seguito un esempio:
https://dati.beniculturali.it/lodview-arco/resource/HistoricOrArtisticProperty/1200163446.html
e la relativa scheda di catalogo
![immagine](https://user-images.githubusercontent.com/42745789/86098313-38eb9980-bab6-11ea-94df-4331fbb84ac0.png)

**Comment by margherita-porena** [comment]
The issue has been solved with commit 302a866
