### ISSUE TITLE
Manca collegamento tra il bene e la Denominazione raccolta?

### ISSUE THREAD

**Issue by ICCD-MiBACT** [ICCD-MiBACT/ArCo#95]
Dove è mappata l’info corrispondente a LDCM (Denominazione raccolta)? 
Serve un elemento nell’ontologia per rappresentare la Denominazione raccolta ( che di solito è dentro un CIS). AL momento sembrerebbe non esserci o meglio LDCM non ha il collegamento con i singoli beni della Collezione che invece sono unificati sotto l’unico Site (che come dicevo sopra è pure moltiplicato a livello di URI).

Nel creare un solo Site, il CNR non usa LDCM per disambiguare la diversa Collection a cui sono collegate le opere nel medesimo Site 
Ad esempio qui
https://dati.beniculturali.it/lodview-arco/resource/Site/4853e9509530012308ed63c4e632be85.html
si raccolgono informazioni di LDCM di schede diverse:
12 00163330
12 00959894
collegate allo stesso Palazzo Venezia, invece andrebbero collegate a due collezioni diverse che stanno entrambe nello stesso Palazzo di Venezia.

**Comment by margherita-porena** [comment]
The issue has been closed with commit  6fcd5ed
