### ISSUE TITLE
URI address e site - verifica urgente

### ISSUE THREAD

**Issue by ICCD-MiBACT** [ICCD-MiBACT/ArCo#96]
Nel momento in cui avviene la produzione dei LOD per i Contenitori fisici c’è un problema sulle URI degli address e dei site.  Vedi ad esempio queste URI, che si riferiscono tutte a Palazzo Venezia:
https://dati.beniculturali.it/lodview-arco/resource/Site/ad3ff364a416dc0d687e8652775ac50f.html
https://dati.beniculturali.it/lodview-arco/resource/Site/5fb8cbf17fc9198500bf4d8f4c93ad6c.html
https://dati.beniculturali.it/lodview-arco/resource/Site/b3230794d166dec29efd5b7874b550ca.html
https://dati.beniculturali.it/lodview-arco/resource/Site/4dabeb2731b4b88a57f71fe4a6ebeb48.html
https://dati.beniculturali.it/lodview-arco/resource/Site/6d427b40635665f8777c322e9de26732.html
https://dati.beniculturali.it/lodview-arco/resource/Site/4853e9509530012308ed63c4e632be85.html

In alcuni casi basterebbe non considerare il campo Nazione per creare l’URI (in molte schede di catalogo è mancante, ma tanto dovrebbe essere sempre Italia). In altri casi non si capisce perché le URI vengono diverse.
In ogni caso andrebbe risolto, eventualmente procedendo ad allineamenti tramite sameAs tra loro e allo stesso record del DBUnico in modo che Regesta gestisca la visualizzazione sul sito

**Comment by margherita-porena** [comment]
Per quanto riguarda la creazione di diverse uri per lo stesso Site, abbiamo controllato il caso indicato ed il problema risulta essere nella diversa compilazione del campo LDCU-Indicazioni viabilistiche (usato per creare le uri dei site, insieme ad altri campi), perché troviamo dati diversi per ogni uri.
Per quanto riguarda l'allineamento con i site del DBUnico, gli allineamenti sono eseguiti dopo ogni release.
