### ISSUE TITLE
Quale è la prefLabel e quale l'altLabel di queste entità?

### ISSUE THREAD

**Issue by ICCD-MiBACT** [ICCD-MiBACT/ArCo#97]
Questi sono solo due esempi. Perchè sono tutte label? Avete elementi per capire quale è la prefLabel?
https://dati.beniculturali.it/lodview-arco/resource/CulturalScope/ambito-italiano.html

https://dati.beniculturali.it/lodview-arco/resource/Subject/4bc976abbf58ef93ecb0dc6b16ec1172.html

**Comment by margherita-porena** [comment]
The issue has been solved with commit d4d3931
