### ISSUE TITLE
Problema nella generazione dei dati (mantenimento valori di origine)

### ISSUE THREAD

**Issue by ICCD-MiBACT** [ICCD-MiBACT/ArCo#98]
Prendo ad esempio questo dato: https://dati.beniculturali.it/lodview-arco/resource/CulturalScope/ambito-italiano.html
Esso schiaccia i vari valori (ambito italiano, ambito italiano (?) , ambito italiano ? , AMBITO ITALIANO) in una unica entità cui collega un certo numero di opere d'arte. Ma per gli storici dell'arte una cosa è dire "ambito italiano", un'altra è dire "ambito italiano?"....

Ok lo schiacciamento delle entità ma nelle schede di origine va preservato il valore inserito dal catalogatore

**Comment by margherita-porena** [comment]
L'issue è stata risolta con il commit d4d3931.
Per risolvere questa issue abbiamo lasciato una unica uri per identificare l'ambito (in modo da facilitare la ricerca per chi volesse trovare le opere di uno stesso ambito, anche se di dubbia attribuzione), ma abbiamo introdotto la dp arco-cd:dubiuosAuthorshipAttribution per distinguere le attribuzioni dubbie dalle altre.
